### ISSUE TITLE
[docs] Fix duplication on getting started pages and api calls

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-nodejs#1023]
There's a fair amount of duplication in the documentation that I'd like to explore removing. Sections like this are duplicated across all getting started pages:

https://github.com/elastic/apm-agent-nodejs/blob/9e3696cb25b03b2c68a7c4b7ab9dedc54309bdd3/docs/express.asciidoc#L171-L184

Sections like this are duplicated across similar api calls. Although, I'm not sure if this particular example makes much sense to change:
https://github.com/elastic/apm-agent-nodejs/blob/9e3696cb25b03b2c68a7c4b7ab9dedc54309bdd3/docs/transaction-api.asciidoc#L100-L105

There are ways we can maintain this identical information in a single location and include it where it is necessary. This will prevent having to update the same information in multiple places as witnessed in https://github.com/elastic/apm-agent-nodejs/pull/1019

**Comment by Qard** [comment]
Might be a good idea to nest the "Getting Started" docs under a generic parent doc that intros the general concepts before linking to the framework-specific stuff. We could do it similar to the API Reference parent page, but with a bit more depth. Certainly I think it'd be good to reduce the top-level pages--half the top-level links currently are getting started guides. 🤔

**Comment by bmorelli25** [comment]
For sure! I've actually been working on a design doc for standardizing certain agent documentation sections. The myriad of top-level getting started links in the Node agent is something that I'd definitely like to address. I like the idea of also moving general concepts to the parent getting started section!

**Comment by watson** [comment]
I like that we have "one page" that an express user can go to and read all they need to get started. It would be a shame if they first had to go to a page that contained all the getting started info that was the same no matter the framework and then had to go to another page that only contained the info unique to Express.

But I agree that there's currently a lot of duplication, which would be nice to reduce. Though maintaining it has so far not been an issue, mainly because it so far hasn't changed much (at all?) over the last many years.
