### ISSUE TITLE
Async-hooks error in Node 10.15.2

### ISSUE THREAD

**Issue by alogishetty** [elastic/apm-agent-nodejs#1075]
```
Failed to compile
./node_modules/elastic-apm-node/lib/instrumentation/async-hooks.js
Module not found: Can't resolve 'async_hooks' in '/Users/alogishe/workspace/PCF/on-borading-ui/node_modules/elastic-apm-node/lib/instrumentation'
```

I have also tried to add asyncHooks value to False but it still failed
```javascript
var agent = require("elastic-apm-node").start({
	// Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
	serviceName: "app_name",
	// Set custom APM Server URL (default: http://localhost:8200)
	serverUrl: "http://0.0.0.0:8200",
	asyncHooks: false
});
```

**Comment by watson** [comment]
The `async_hooks` module has been part of core since Node.js version 8. Could it be that your environment somehow loads an old version of Node.js even though you have a newer version installed?

If you in your code try to run `console.log('Running Node.js version:', process.version)`, does it still output version 10?

**Comment by Qard** [comment]
Are you trying to use it with webpack? That looks like the error you get when trying to bundle Node.js code that uses non-browser-compatible code without explicitly telling webpack to allow it. See: https://webpack.js.org/configuration/node#other-node-core-libraries

**Comment by watson** [comment]
Closing for now due to lack of response. Just add a comment if you want it to be reopened 😃

**Comment by daucuong** [comment]
I got same issue when install apm agent
https://www.screencast.com/t/GLRkXqPf

Nodejs v10.16.0

**Comment by watson** [comment]
@daucuong did you try https://github.com/elastic/apm-agent-nodejs/issues/1075#issuecomment-494587021 ?

**Comment by kjk515** [comment]
Can you let me know how to set the webpack 'node' option?

**Comment by stas-raranetskyi** [comment]
I got same issue when install apm agent v3.10.0
https://prnt.sc/x7xdfn

Nodejs v14.14.0

**Comment by Alfred-kai** [comment]
I got same issue when install apm agent,NodeJS v14.16

**Comment by diego3** [comment]
I got same issue when install  "elastic-apm-node": "^3.18.0" and NodeJS v14.17.3

**Comment by astorm** [comment]
@diego3, @Alfred-kai Thanks for reporting.  

Speaking generally, `async_hooks` has been a part of Node.js for a while now so it's curious to see error complaining about it missing.  Our next steps here will be to figure out why your particular invocation of node can't seem to find async_hooks. 

To that end, we have a few clarifying questions.

1. Where did you get your Node.js executable from? (apt/yum on _some linux distro_? manual install  or compile from _somewhere_? etc.)
2. The error reported is _Failed to compile_ -- could you share the command line invocation that's leading to this error?

Our end goal is to reproduce the behavior you're seeing in order to diagnose the problem.  Once we have a repro we'll be better able to advise.

**Comment by Qard** [comment]
That's a webpack error. For some reason it's trying to bundle up some code that requires async_hooks into a webpack build.

**Comment by tony123S** [comment]
v16.19.0 still facing this error
```

Failed to compile.

./node_modules/undici/lib/api/api-request.js
Module not found: Can't resolve 'async_hooks' in 'C:\Users\nick_\VSCodeProjects\xxx\nft\node_modules\undici\lib\api'
```
