### ISSUE TITLE
Make it possible to restart a single Jenkins CI build

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1140]
Today there's no way to restart a single failing build in case it fails for reasons unrelated to the code (e.g. our CI servers crashing or being unresponsive). This means that we'll have to run the entire test suite one more time, which takes over an hour.

Allowing us to restart just a single build will save us a lot of time and CI resources.

**Comment by watson** [comment]
@elastic/observablt-robots what is the possibility to add this feature?

**Comment by mdelapenya** [comment]
Because of the distributed nature of the Jenkins cluster (master and ephemeral workers), restarting a pipeline from an intermediate stage could not be possible in most of the cases, as it's very likely that some build outputs would have been created in previous steps and not available in the current (and ephemeral) worker.

As part of this week grooming, I would close this issue

👎 (which means my vote to close it)

**Comment by kuisathaverat** [comment]
a build pipeline is an atomic flow that should success as a unique piece of true if we think we need to relaunch it from some point, we would have an issue in someplace (flakiness, infrastructure, design, ...) that we must resolve. So there is no reason to relaunch a build from some stage, there are issues to resolve, or we need to re-design the pipeline.
