### ISSUE TITLE
APM Server requests are sometimes reported as spans

### ISSUE THREAD

**Issue by bradennapier** [elastic/apm-agent-nodejs#1168]
**Describe the bug**

When i look at the apm logs I noticed that every one has a 10 second timeout for the `intake/v2/events` requests that occur during a distributed trace.

We use the managed elastic cloud so don't think we set anything up wrong - its just the given parameters here.

I did notice that if i make the request using http to the endpoint that is failing it does hang forever wheras if i use https i get "error: invalid token" - so I am thinking the agent is not using https or something?

Another thing to note is this only seems to happen with a distributed trace as far as I can tell.  At least the only time I see it happen is when the `worker` here makes the `api-test` request and its within the second service there that the timeout is occurring.

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux Ubuntu v16
- Node.js version: 10.15.1
- APM Server version: v7.1.1
- Agent version: 2.11.6

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [x] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

(both the above methods cause it)

**Additional context**

![image](https://user-images.githubusercontent.com/15365418/60243853-fd4c3d00-986d-11e9-87b2-7da735caf612.png)

here is the stack that apm reports.  

```
/v1/node_modules/elastic-apm-http-client/index.js in StreamChopper.<anonymous> at line 326
events.js in emit at line 189
/v1/node_modules/stream-chopper/index.js in StreamChopper._startStream at line 109
/v1/node_modules/stream-chopper/index.js in StreamChopper._write at line 192
/v1/node_modules/stream-chopper/node_modules/readable-stream/lib/_stream_writable.js in doWrite at line 405
/v1/node_modules/stream-chopper/node_modules/readable-stream/lib/_stream_writable.js in writeOrBuffer at line 394
/v1/node_modules/stream-chopper/node_modules/readable-stream/lib/_stream_writable.js in Writable.write at line 303
/v1/node_modules/elastic-apm-http-client/index.js in Client._writevCleaned at line 208
/v1/node_modules/elastic-apm-http-client/index.js in processBatch at line 181
/v1/node_modules/elastic-apm-http-client/index.js in Client._writev at line 199
/v1/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js in doWrite at line 405
/v1/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js in clearBuffer at line 501
/v1/node_modules/elastic-apm-http-client/node_modules/readable-stream/lib/_stream_writable.js in Writable.uncork at line 317
/v1/node_modules/elastic-apm-http-client/index.js in _corkTimer.setTimeout at line 228
timers.js in ontimeout at line 436
timers.js in tryOnTimeout at line 300
timers.js in listOnTimeout at line 263
timers.js in processTimers at line 223
````

**Comment by watson** [comment]
Thanks for reporting this bug. The extra span for the APM Server seems like an issue we had previously (#732), which I thought was fixed. But apparently, it can still happen.

This is only an issue related to how we collect spans and shouldn't impact the performance of your application. Request to the APM Server happens asynchronously and doesn't block the responses of any of your requests.

The agent makes a new streaming HTTP request to the APM Server at regular intervals, say every 10 seconds. Then whatever request in your application happens to be active just when the agent decides to make this request, will wrongly have this request associated with it in its trace. So while I agree it looks weird and should be fixed, it shouldn't impact your application in any way.

> I did notice that if i make the request using http to the endpoint that is failing it does hang forever wheras if i use https i get "error: invalid token" - so I am thinking the agent is not using https or something?

The agent uses either HTTP or HTTPS depending on the `serverUrl` config option. For APM hosted on Elastic Cloud we only support HTTPS, which means that your `serverUrl` config option should also start with `https://`, which it does if you copied it from the provided config option when setting up APM. If you try to use HTTP it will hang - I think because the load balancer doesn't know how to deal with that (I guess that could be improved so that the connection is just dropped).

The error with "invalid token" when you make the request your self, is because the API needs your `secretToken` to validate the request. So if you just make a simple curl request and doesn't provide the secret token in a header, this is the expected error message.

The reason why the span to the APM Server is so long is that we use a streaming HTTP request. We open up a new HTTP request at regular intervals and send all the APM data we collect over that active HTTP request. This way we don't need to keep the collected data in memory, but can send it right away, and we don't have to deal with the overhead of opening up new TCP sockets for each piece of data we collect.

**Comment by bradennapier** [comment]
Thank you for your reply. It does seem odd that the length is the exact length of the default timeout interval. The rest does makes sense though! Yes the server url being used is https.---- On Thu, 27 Jun 2019 02:14:41 -0700  Thomas Watson<notifications@github.com> wrote ----Thanks for reporting this bug. The extra span for the APM Server seems like an issue we had previously (#732), which I thought was fixed. But apparently, it can still happen. 
This is only an issue related to how we collect spans and shouldn't impact the performance of your application. Request to the APM Server happens asynchronously and doesn't block the responses of any of your requests. 
The agent makes a new streaming HTTP request to the APM Server at regular intervals, say every 10 seconds. Then whatever request in your application happens to be active just when the agent decides to make this request, will wrongly have this request associated with it in its trace. So while I agree it looks weird and should be fixed, it shouldn't impact your application in any way. 
 
I did notice that if i make the request using http to the endpoint that is failing it does hang forever wheras if i use https i get "error: invalid token" - so I am thinking the agent is not using https or something? 
 
The agent uses either HTTP or HTTPS depending on the serverUrl config option. For APM hosted on Elastic Cloud we only support HTTPS, which means that your serverUrl config option should also start with https://, which it does if you copied it from the provided config option when setting up APM. If you try to use HTTP it will hang - I think because the load balancer doesn't know how to deal with that (I guess that could be improved so that the connection is just dropped). 
The error with "invalid token" when you make the request your self, is because the API needs your secretToken to validate the request. So if you just make a simple curl request and doesn't provide the secret token in a header, this is the expected error message. 
The reason why the span to the APM Server is so long is that we use a streaming HTTP request. We open up a new HTTP request at regular intervals and send all the APM data we collect over that active HTTP request. This way we don't need to keep the collected data in memory, but can send it right away, and we don't have to deal with the overhead of opening up new TCP sockets for each piece of data we collect.

**Comment by watson** [comment]
It's just a coincidence that [`apiRequestTime`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#api-request-time) is also 10 seconds. So as long as the outgoing request doesn't get too big it will last 10s. If it gets above the limit specified using [`apiRequestSize`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#api-request-size) it will end earlier.

**Comment by dennis4scotty** [comment]
Ah would be great to see this being fixed and information more concise.
When do you plan to release a fix for this?
