### ISSUE TITLE
Ensure npm is only updated on Node.js 8.1.* or below in Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1203]
For details see this discussion:
https://github.com/elastic/apm-agent-nodejs/pull/1202#discussion_r301544610

In bash, I'd do something like this, but I'm not sure about Dockerfiles:

```bash
FULL_NODE_VERSION=`node --version`
[[ $FULL_NODE_VERSION =~ [0-9]+ ]]
MAJOR_NODE_VERSION="${BASH_REMATCH[0]}"

if [[ $MAJOR_NODE_VERSION -le 7 ]] || [[ $FULL_NODE_VERSION == v8.1.* ]]
then
  npm install npm@latest
fi
```

**Comment by kuisathaverat** [comment]
right now, for versions lower or equal 8 we are using npm@6.9.0, the last version of npm is 6.10.0, it has about a week. I think that does not worth to add more logic to the script that updates the npm to the latest because it is more complex that the one you propose that does not detect 8.0.X versions for example,  it does not add value on versions lower or equal 8, also we hit an issue with node 6 with the last version of npm that avoid downloading all the dependencies.

**Comment by watson** [comment]
This issue I wanted to solve was wrongly updating npm on the latest version of Node.js 8, which could lead to false positives in our tests (as I want to mimic the users' environment as closely as possible). In a perfect world, I wouldn't want to upgrade npm on _any_ version of Node.js, but we have to do it for Node.js 8.1 and below for because of an issue with the version of npm that ships with those versions that made our tests fail.

We don't care about Node.js 8.0.x as that contains a bug that will make our test suite fail anyway (hence why we're testing against v8.1.x instead of v8.0.x).

But if this is too complicated to do in Jenkins, let's drop it then?

**Comment by trentm** [comment]
I believe this is obsolete. Node v8.6.0 is the minimum now.
