### ISSUE TITLE
NodeJS v10.16.1 crash while using elastic-apm-node

### ISSUE THREAD

**Issue by ronkorland** [elastic/apm-agent-nodejs#1261]
**Describe the bug**
Since I have started using elastic-apm-node, it has started throwing `Could not process callsites` errors and node process to crash :

Errors:
```
could not capture stack trace for span { span: '627f2bf485604de9',
  parent: '5c26008e6557b10e',
  trace: '5d8bc7df6238f7bf83bccf7a95c8ce0f',
  name: 'GET',
  type: 'cache.redis',
  err: 'Could not process callsites' }

could not capture stack trace for span { span: 'e1e0625c65b656ca',
  parent: '6ed44490829eabca',
  trace: 'c4f78b304cf844d368b5830712c5c88f',
  name: 'SELECT FROM `XXXX`',
  type: 'db.mysql.query',
  err: 'Could not process callsites' }
```

Crash error:
```
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**To Reproduce**
Use this config 
node v10.16.1 + npm v6.9.0 (docker base image: node:10-slim)
elastic-apm-node v2.13.0
apm-server v6.5.4
mongoose v5.6.2
ioredis v4.3.0
mysql v2.16.0
mysql2 v1.6.4 

**Environment (please complete the following information)**
- Docker base image: node:10-slim
- OS: Debian
- Node.js version: 10.16.1
- APM Server version: 6.5.4
- Agent version: 2.13.0

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Comment by watson** [comment]
The `npm-lifecycle` module is not part of the Elastic APM Node.js agent, so I don't think your crash is related to the agent.

You get the `could not capture stack trace for span` warning because the stack trace collected for the span for some reason doesn't look like a valid stack trace. This is most likely because another module in your dependency tree is overwriting the v8 stack trace function in a destructive way which means we don't get access to the raw callsite objects.

Try to search your code and `node_modules` folder for the string "Error.prepareStackTrace" and let me know which modules you find it in.

**Comment by watson** [comment]
I can see that it's logged on the warning level, but I think that's actually too aggressive. We should maybe consider only logging it on the debug level as it's nothing critical and it probably just confuses people. What do you think @Qard?

**Comment by ronkorland** [comment]
I found this sting inside several `node_modeuls`:
```
Targets
    Occurrences of 'Error.prepareStackTrace' in Directory /xxx/xxx/xxx/xxx/node_modules
Found Occurrences  (60 usages found)
    Unclassified occurrence  (60 usages found)
        node_modules/bindings  (3 usages found)
            bindings.js  (3 usages found)
                146 var origPST = Error.prepareStackTrace,
                153 Error.prepareStackTrace = function(e, st) {
                173 Error.prepareStackTrace = origPST;
        node_modules/bunyan/lib  (3 usages found)
            bunyan.js  (3 usages found)
                187 var savePrepare = Error.prepareStackTrace;
                190 Error.prepareStackTrace = function (_, stack) {
                205 Error.prepareStackTrace = savePrepare;
        node_modules/caller-callsite/node_modules/callsites  (3 usages found)
            index.js  (3 usages found)
                3 const _ = Error.prepareStackTrace;
                4 Error.prepareStackTrace = (_, stack) => stack;
                6 Error.prepareStackTrace = _;
        node_modules/callsite  (3 usages found)
            index.js  (3 usages found)
                3 var orig = Error.prepareStackTrace;
                4 Error.prepareStackTrace = function(_, stack){ return stack; };
                8 Error.prepareStackTrace = orig;
        node_modules/callsites  (3 usages found)
            index.js  (3 usages found)
                4 const _prepareStackTrace = Error.prepareStackTrace;
                5 Error.prepareStackTrace = (_, stack) => stack;
                7 Error.prepareStackTrace = _prepareStackTrace;
        node_modules/depd  (3 usages found)
            index.js  (3 usages found)
                368 var prep = Error.prepareStackTrace
                370 Error.prepareStackTrace = prepareObjectStackTrace
                379 Error.prepareStackTrace = prep
        node_modules/depd/lib/compat  (3 usages found)
            index.js  (3 usages found)
                24 var prep = Error.prepareStackTrace
                30 Error.prepareStackTrace = prepareObjectStackTrace
                39 Error.prepareStackTrace = prep
        node_modules/error-callsites  (2 usages found)
            index.js  (2 usages found)
                5 var orig = Error.prepareStackTrace
                6 Error.prepareStackTrace = function (err, callsites) {
        node_modules/get-caller-file  (3 usages found)
            index.js  (3 usages found)
                9 var oldPrepareStackTrace = Error.prepareStackTrace;
                10 Error.prepareStackTrace = function(err, stack) { return stack; };
                12 Error.prepareStackTrace = oldPrepareStackTrace;
        node_modules/hoek/lib  (3 usages found)
            index.js  (3 usages found)
                662 var v8 = Error.prepareStackTrace;
                663 Error.prepareStackTrace = function (err, stack) {
                672 Error.prepareStackTrace = v8;
        node_modules/morgan/node_modules/depd  (3 usages found)
            index.js  (3 usages found)
                376 var prep = Error.prepareStackTrace
                378 Error.prepareStackTrace = prepareObjectStackTrace
                387 Error.prepareStackTrace = prep
        node_modules/morgan/node_modules/depd/lib/compat  (3 usages found)
            index.js  (3 usages found)
                18 var prep = Error.prepareStackTrace
                24 Error.prepareStackTrace = prepareObjectStackTrace
                33 Error.prepareStackTrace = prep
        node_modules/nyc/node_modules/get-caller-file  (3 usages found)
            index.js  (3 usages found)
                9 var oldPrepareStackTrace = Error.prepareStackTrace;
                10 Error.prepareStackTrace = function(err, stack) { return stack; };
                12 Error.prepareStackTrace = oldPrepareStackTrace;
        node_modules/nyc/node_modules/resolve/lib  (3 usages found)
            caller.js  (3 usages found)
                3 var origPrepareStackTrace = Error.prepareStackTrace;
                4 Error.prepareStackTrace = function (_, stack) { return stack; };
                6 Error.prepareStackTrace = origPrepareStackTrace;
        node_modules/proxyquire/node_modules/resolve/lib  (3 usages found)
            caller.js  (3 usages found)
                3 var origPrepareStackTrace = Error.prepareStackTrace;
                4 Error.prepareStackTrace = function (_, stack) { return stack; };
                6 Error.prepareStackTrace = origPrepareStackTrace;
        node_modules/require-uncached/node_modules/callsites  (3 usages found)
            index.js  (3 usages found)
                3 var _ = Error.prepareStackTrace;
                4 Error.prepareStackTrace = function (_, stack) { return stack };
                6 Error.prepareStackTrace = _;
        node_modules/resolve/lib  (3 usages found)
            caller.js  (3 usages found)
                3 var origPrepareStackTrace = Error.prepareStackTrace;
                4 Error.prepareStackTrace = function (_, stack) { return stack; };
                6 Error.prepareStackTrace = origPrepareStackTrace;
        node_modules/sequelize/lib  (3 usages found)
            utils.js  (3 usages found)
                362 var orig = Error.prepareStackTrace;
                363 Error.prepareStackTrace = function(_, stack) { return stack; };
                367 Error.prepareStackTrace = orig;
        node_modules/source-map-support  (1 usage found)
            source-map-support.js  (1 usage found)
                508 Error.prepareStackTrace = prepareStackTrace;
        node_modules/stripe  (2 usages found)
            tags  (2 usages found)
                1339 Error.prepareStackTrace	node_modules/resolve/lib/caller.js	/^    Error.prepareStackTrace = function (_, stack) { return stack };$/;"	f
                1340 Error.prepareStackTrace	node_modules/stack-trace/lib/stack-trace.js	/^  Error.prepareStackTrace = function(dummyObject, v8StackTrace) {$/;"	f
        node_modules/ts-node/node_modules/source-map-support  (1 usage found)
            source-map-support.js  (1 usage found)
                537 Error.prepareStackTrace = prepareStackTrace;
        node_modules/twilio/node_modules/hoek/lib  (3 usages found)
            index.js  (3 usages found)
                674 const v8 = Error.prepareStackTrace;
                675 Error.prepareStackTrace = function (_, stack) {
                684 Error.prepareStackTrace = v8;
Usages in generated code  (4 usages found)
    Unclassified occurrence  (4 usages found)
        node_modules/ajv/dist  (1 usage found)
            nodent.min.js  (1 usage found)
                8 Error.prepareStackTrace
        node_modules/source-map-support  (1 usage found)
            browser-source-map-support.js  (1 usage found)
                110 Error.prepareStackTrace
        node_modules/ts-node/node_modules/source-map-support  (1 usage found)
            browser-source-map-support.js  (1 usage found)
                112 Error.prepareStackTrace
        node_modules/twilio/node_modules/ajv/dist  (1 usage found)
            nodent.min.js  (1 usage found)
                2 Error.prepareStackTrace

```

**Comment by ronkorland** [comment]
If you prefer I can run the process with any env var for more info

**Comment by watson** [comment]
Btw, now that think about it: `npm-lifecycle` probably comes from using `npm start` to start your app, but in any case, this is not a warning that crashes the app, so I still think the crash is unrelated.

**Comment by watson** [comment]
Thanks for sharing the list... I'll have a look to see if any of those modules might mess with our ability to collect stack traces. But I think this is the culprit. The only solution to these kinds of issues is unfortunately to submit a PR to the offending module.

**Comment by ronkorland** [comment]
If you can help me to find the problematic package it will be great so I can open an issue

**Comment by Qard** [comment]
re: log level -- I'm fine with changing that to debug.

**Comment by ronkorland** [comment]
Great, thanks for taking care of the log issue - what would be a good way to move forward with the crash? Currently this is blocking for us and we can't deploy because of it.

**Comment by watson** [comment]
What leads you to believe that the crash is related to this module? The stack trace just points to npm and the error message says that the program exited with code 1.

**Comment by ronkorland** [comment]
I run my self-test with and without this module.
When the module enabled (required) my application crashed

**Comment by watson** [comment]
A crash would always give you a stack trace. The stack trace listed above looks like it comes from a parent process that detects a child process has exited - not a crash. If the child process exists because of a crash, that crash should be visible in the STDERR output of the child process own. If you look in that log, you should see the root cause.

**Comment by ronkorland** [comment]
I added handlers to `uncaughtException` and `unhandledRejection` I still don't see any error

**Comment by watson** [comment]
How are you starting the child process?

**Comment by ronkorland** [comment]
package.json: 
```
  "scripts": {
    xxx
    "start": "node --max-old-space-size=3072 server.js"
  },
```

**Comment by watson** [comment]
That's your main process (`server.js`). The stack trace in the issue description comes from the `child_process` core module. If I read it correctly, it simply says that your node app (`server.js`) itself starts a child process. It's this child process which apparently exists with code 1. Not the main process started by the `start` script. Does your application start any child processes?

**Comment by ronkorland** [comment]
We don't run any child processes

**Comment by watson** [comment]
Then maybe it's related to how you start the application. Do you run `npm start` or do you use a tool like pm2 to monitor and keep the process running?

**Comment by ronkorland** [comment]
We just do `npm start` command

**Comment by watson** [comment]
The stack trace above actually comes from npm itself (from the log file it generates if the application started using `npm start` exits with a non-zero exit code). In my case they are located in `/Users/watson/.npm/_logs/*.log`.

That's why it's not showing the actual reason why the application crashed. It's just saying that it exited with exit code 1.

I assume you found this log file by reading the output in the application log, eg:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foo@1.0.0 start: `node --max-old-space-size=3072 index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/watson/.npm/_logs/2019-08-13T14_32_00_089Z-debug.log
```

Right above this output is where Node.js normally will display the actual stack trace if the exit was caused by an uncaught exception. If the Elastic APM agent catches the exception (which it will by default), it will send it to the APM Server before exiting. In that case, you'll see a logline like the following just before the program exits:

```
Sending error to Elastic APM { id: 'a5b25cb24c9a055979ca01d93159c9cc' }
```

You can then search for this `error.id` in the query bar in the Kibana APM UI, eg:

```
error.id: a5b25cb24c9a055979ca01d93159c9cc
```

Alternatively you can temporarily turn of the feature of the APM agent that catches exceptions using this config:

```js
captureExceptions: false
```

_Read more about that here: https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-exceptions_

**Comment by ronkorland** [comment]
When I changed ```captureExceptions: false``` my sever process not crashed looks like it's related to this feature in apm module

**Comment by watson** [comment]
There's no way to safely recover from an uncaught exception in Node.js. So when a Node.js process experiences an uncaught exception it crashes.

You can attach an [`uncaughtException`](https://nodejs.org/api/process.html#process_event_uncaughtexception) event listener to the process which allows you to perform any last-minute operation before shutting down the process, but if you do so, it's now your responsibility to exit the process. This is achieved by performing a `process.exit(1)` after you're done.

From what you've told me so far, it sounds like you have a listener set up for `uncaughtException` which doesn't exit the process - [this is not safe and not recommended](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly).

When you install the Node.js agent it will itself attach an `uncaughtException` listener to be able to send the details about the uncaught exception to the APM Server, after which it exits the process with a non-zero exit code as it's supposed to.

So I think that the reason why you don't experience what you call a "crash" (which is really just the process exiting) without the Node.js agent installed is that you accidentally keep the process alive after the uncaught exception. And the reason why the process suddenly exits when you install the agent is that the agent automatically exits the process after it detects an uncaught exception. So the crash isn't caused by the Node.js agent but is a result of the uncaught exception elsewhere in your code, which is just properly handled by the agent.

If you need to run any code after an uncaught exception has occurred, while also taking advantage of the agents' ability to log these errors, I recommend instead that you use the [`agent.handleUncaughtExceptions()`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-handle-uncaught-exceptions) API. With this API, you can technically also choose not to exit the process, but this is not advisable and will cause your program to run in an unknown state and will introduce other bugs down the line (see link above).

**Comment by ronkorland** [comment]
@watson Thank you very much

**Comment by watson** [comment]
FYI, I've noticed that the module `source-map-support` can cause this the issue of the missing span stack traces. We're looking into if it can be easily worked around it.

**Comment by bearfact** [comment]
@watson any update on the ```source-map-support``` problem?  I believe I may be experiencing missing mongodb data in my transactions because of this.
