### ISSUE TITLE
Jenkins doesn't detect invalid commit messages

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1313]
We are linting the PR commit messages as part of our Jenkins pipeline, but as seen in #1312, it somehow doesn't work and simply just marks commits as ok even though they are not.

**Comment by v1v** [comment]
For the record:

https://github.com/elastic/apm-agent-nodejs/blob/75ee4510bc3db5b38464dfd0a85eea97afe81e9a/.ci/scripts/lint-commits.sh#L14 does use the env variable GIT_BASE_COMMIT which seems to match the latest commit from the master branch rather than the commit from the PR itself:

```
commitlint --from=origin/master --to=75ee4510bc3db5b38464dfd0a85eea97afe81e9a
```

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/PR-1312/1/pipeline/132#step-307-log-98


I'd rather suggest to:
- Avoid using env variables within the script and pass those variables as parameters to the script itself.

**Comment by v1v** [comment]
This is causes after merging https://github.com/elastic/apm-agent-nodejs/pull/1304 as the env variable seems to be pointing out to another commit somehow.

**Comment by watson** [comment]
This turned out to be a bug in #1312
