### ISSUE TITLE
Support node.js v13 in engines

### ISSUE THREAD

**Issue by danieljuhl** [elastic/apm-agent-nodejs#1516]
Should we consider allowing node.js v13?

Right now engines in package.json is restricted to node.js v12 as the newest version. Is there any issues or reasons to not allow v13 at the moment?

**Comment by talkquazi** [comment]
Related to this post. I ran into a bug when using yarn to install elastic-apm-node in node 13.

[3/5] Fetching packages...
error elastic-apm-node@3.1.0: The engine "node" is incompatible with this module. Expected version "^8.6.0 || 10 || 12". Got "13.0.1"
error Found incompatible module.

The fix is probably as simple as modifying the package.json file to allow || 13 in the engines.node value.

**Comment by Qard** [comment]
Yes, Node.js 13 should be added to the package.json. As far as I can tell, it should work fine.

**Comment by axw** [comment]
I've just released v3.2.0, which adds 13 to the list.
