### ISSUE TITLE
Node.js nightly/rc tests are all failing on Jenkins

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1537]
Example: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/289/pipeline/6250

**Comment by watson** [comment]
ping @elastic/observablt-robots

**Comment by mdelapenya** [comment]
It seems that the APM Server and the memcached server are not available:

```
[2019-11-20T07:57:32.621Z] node_tests_1     | APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
[2019-11-20T07:59:24.228Z] node_tests_1     | not ok 1 Error: getaddrinfo ENOTFOUND memcached memcached:11211
```
Looking into it

**Comment by mdelapenya** [comment]
We realised that memcached was added here: 6096fbdcf935b3cd2ac668bec7bdebb7aca94f9f (See PR https://github.com/elastic/apm-agent-nodejs/pull/1144).

The edge tests were added here https://github.com/elastic/apm-agent-nodejs/pull/1227, one month before, so we suspect that the memcached PR was not covering the edge use cases.

The Edge test execution should include memcached so that the failure does not appear again.
