### ISSUE TITLE
Capture custom error fails

### ISSUE THREAD

**Issue by danieljuhl** [elastic/apm-agent-nodejs#156]
The docs (https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-capture-error) states, that `error` can be an `Error` object, a message string or a special parameterized object.

I try to capture some custom errors (passed from client-side to the server as simple strings). I'm using `apm.captureError(error[, options][, callback])`

If I provide an `Error` object (eg. `new Error(myCustomMessage)`), everything works as expected (except I try to get rid of the stack trace for that specific capture).

If instead, I provide `myCustomMessage` (a simple string) directly to `apm.captureError()`, the errors is logged as "N/A" (and stack trace is also N/A).

Last, the `special parameterized object` is not described at any place. What is the structure? As I hope this can be useful in my case.

I actually have a stacktrace (captured by the client) that I would love to include in my APM error.

**Comment by watson** [comment]
## Missing message

This is a known issue with the Kibana APM plugin from [X-Pack](https://www.elastic.co/products/x-pack), which I imagine you're using? It will be fixed in version 6.2 of X-Pack. You shouldn't see this issue if you're using the Kibana Dashboards that come bundled with APM Server. But if you are, please let us know.

### Technical explanation

When ever a string or the special parameterized object is captured with `captureError()`, it's stored on the error document in Elasticsearch under the `log` namespace - as opposed to the `exception` namespace if it's an error object that's captured. The Kibana APM Plugin that you get with X-Pack Basic currently don't fall back to showing the `log.message` if `exception.message` is unavailable. As mentioned above, this is fixed in version 6.2 of X-Pack.

### Temporary solution

Before the next release of X-Pack, you can see `log.message` by clicking the "View X occurrences in Discover" button on the error page:

<img width="528" alt="screen shot 2018-01-08 at 13 49 00" src="https://user-images.githubusercontent.com/10602/34671466-0e65b014-f47b-11e7-8960-c916601857a5.png">

Alternatively you can view the error on the Kibana Dashboards which are bundled with the APM Server.

## Missing stack trace

Currently strings and parameterized objects will not have an associated stack trace - only errors will. I've created an issue to add this feature: #160

## Parameterized object

You're right it's not documented. I've created an issue to correct that where you can also read about the format: #159

**Comment by danieljuhl** [comment]
@watson
How do I see the difference between the X-Pack plugin and the bundled dashboard? I would have assumed that we were using the bundled dashboard.

**Comment by danieljuhl** [comment]
I assume that the "APM" menu item is the X-Pack plugin and the various "[APM] ....." dashboards is the bundled dashboards. Correct? In that case, yes, I was using the X-Pack plugin.

**Comment by watson** [comment]
@danieljuhl yes that's correct, you're using the X-Pack plugin then

**Comment by danieljuhl** [comment]
@watson Should we close this issue? You have explained it, created new issues for specific parts, so for now, there should be nothing left in this issue. Right?

I have a simple follow up then, only slightly related. Somehow during our setup/installation of apm-server the index in the dashboard ended as "customname-*", but our index is actually "apm-*". The bundled dashboard was then broken, and even after changing the index in the Saved Objects, they kept being broken. We then removed all the APM saved objects, and expected that I could re-import them. But I can't find a 6.1.1 compatible file. Which Kibana templates should I be importing?

**Comment by watson** [comment]
@danieljuhl I'm not sure about that. Could I get you to raise the question on our [Discuss forum](https://discuss.elastic.co/c/apm) instead?

I'll close this issue for now
