### ISSUE TITLE
CodeCov status indicators not working

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#157]
Even though we landed [a commit in master](https://github.com/elastic/apm-agent-nodejs/commit/8a48b49702ac9f9014245dc5a9156ce4552da6cb) that should prevent CodeCov from posting comments on PR's and instead use GitHub status indicators, we [still get](https://github.com/elastic/apm-agent-nodejs/pull/155#issuecomment-355683450) the comments and the status indicators are nowhere to be found.

More research is needed 😄

**Comment by Qard** [comment]
I dug through the docs and validated the yaml file, but there seems to be nothing wrong with it. The file is definitely being used, because the comments stopped now. I think the PR you linked was based before the codecov.yml commit got merged to elastic-6.2. No sign of status indicators though, even though the configs appear to be valid and there's no mention of any other steps to enable them in their docs. I've emailed them to see if there's something wrong.

**Comment by watson** [comment]
Thanks for investigating 👍 Could it be a permission thing that needs to be enabled on the repo maybe?

**Comment by Qard** [comment]
I don't think so. I appear to have admin permissions on the org.

**Comment by watson** [comment]
It looks like they are working now for some reason:

![image](https://user-images.githubusercontent.com/10602/35637206-d65060ca-06b3-11e8-9006-8defb483f81f.png)

I'll close this then 😃
