### ISSUE TITLE
Option to ignore spans that are shorter than x milliseconds

### ISSUE THREAD

**Issue by SimonSimCity** [elastic/apm-agent-nodejs#1701]
**Is your feature request related to a problem? Please describe.**
Performance is always a question which might get in conflict with monitoring. Here I provide an additional approach/idea to get more useful information by monitoring.

**Describe the solution you'd like**
When looking through the list of performance improvements (https://www.elastic.co/guide/en/apm/agent/nodejs/current/performance-tuning.html) I noticed that - depending on what you're logging - it might be interesting not only to have a limit on spans `transactionMaxSpans` but also to have the option to ignore spans which have a shorter time-span than a given amount. This might also for some applications improve the help this package can bring because e.g. database calls are just mentioned if they take more than `x` milliseconds.

**Comment by watson** [comment]
As you correctly pointed out there's no config option to drop spans shorter than x ms. Howerver, you can implement such a thing pretty simply yourself by adding a [span-filter](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-span-filter).

E.g. here we drop all spans shorter than 10ms:

```js
agent.addSpanFilter(payload => {
  return payload.duration < 10 ? null : payload
})
```

It's worth noting btw that since Node.js is asyncrounous, we can't know how long a span will be before creating the span object it in memory. So it's unfortunately not possible to skip creating the span altogether if the duration is below the decided limit. This is possible with some of our other agents, e.g. the Python agent. So the best you can do is ignore it after it has been created (like we do in the example above). With that approach you save having to serialize the object to JSON, sending it to the APM Server and storing it in Elasticsearch.

Is this an acceptable solution to your problem, or do you still think it's worth creating a config option to control this?

**Comment by SimonSimCity** [comment]
Looks quite good - as you said it's not possible to for-see how long an async operation will take.

I just think that something like this should also be added to the `Performance` section in the tutorials.

**Comment by watson** [comment]
Good point. Let's leave this issue open as a reminder so we can get it in. You're of course also more than welcome to make a PR if you have time ☺️
