### ISSUE TITLE
Relax k8s pod ID discovery regex

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-nodejs#1803]
See elastic/apm#285 and elastic/apm#284

**Comment by astorm** [comment]
We've confirmed that the current parsing of podIDs from `container-info` handles the new test cases from https://github.com/elastic/apm/pull/284

```
12:pids:/kubepods/kubepods/besteffort/pod0e886e9a-3879-45f9-b44d-86ef9df03224/244a65edefdffe31685c42317c9054e71dc1193048cf9459e2a4dd35cbc1dba4
10:cpuset:/kubepods/pod5eadac96-ab58-11ea-b82b-0242ac110009/7fe41c8a2d1da09420117894f11dd91f6c3a44dfeb7d125dc594bd53468861df
```

In order to ensure `container-info` maintains this behavior, we have added these fixtures [to the test suite](https://github.com/Qard/container-info/pull/9).

As a reminder, the "transform podId from underscore_naming to dash-naming" functionality lives in [the HTTP client itself](https://github.com/elastic/apm-agent-nodejs/issues/1803) in order to not disrupt other non-elastic users of the `container-info` package. 

Once the `container-info` PR lands we'll close this out as done. If there's more here that needs to be done please let us know.

**Comment by astorm** [comment]
CI done on https://github.com/Qard/container-info/pull/9, closing this out as done.
