### ISSUE TITLE
Jaeger agent support

### ISSUE THREAD

**Issue by ebuildy** [elastic/apm-agent-nodejs#1961]
**Is your feature request related to a problem? Please describe.**

elasticAPM library is (I believe) one of the most advanced nodejs library for collecting metrics (support many libraries such as ioredis, mysql etc..), it communicates via HTTP to a server. We are afraid to put it as is on production, because HTTP is (under the hood TCP) synchronous and could affect our backend performance.

On other side, there is another cool tracing solution called Jaeger, that speak UDP between client and agent. And cherry on the cake, Jaeger use elasticsearch as storage!

**Describe the solution you'd like**

I would like to use jaeger as backend instead of elastic APM server.

**Describe alternatives you've considered**

* Use another nodejs library (but we love this one!)
* Scale out APM server (but scaling != performance)
* Develop an elastic-apm bridge (app --(UDP)--> bridge --(HTTP)--> elasticAPM server)

**Comment by astorm** [comment]
Thanks for the feature suggestion @ebuildy.

Regarding

> HTTP is (under the hood TCP) synchronous and could affect our backend performance

Is this behavior something you've observed, or something you're still investigating? If it's something you've observed, are the benchmarks something you can share? If you don't have benchmarks, can you share the general use case where the TCP connections are causing problems for you? We ask because we're always intersted in ways we can optimize the Agent's HTTP connection to APM Server.  While Node.js doesn't give us control over any synchronous things happening at the TCP level, the HTTP connections made in the agent are "asynchronous from a Node.js standpoint", so if you're seeing performance problems here we'd like to know more. 

Given our current priorities and limited time/attention, communicating with a jaeger collection endpoint is not a part of our current plans.  It's our understanding that the CNCF's current priorities are focused on the Open Telemetry collector and not on jaeger specifically.  It's unlikely we'll be able to prioritize having the agent speak directly with a jaeger endpoint -- although if enough people ask about it that can always change. (hint hint)

Also -- while it's not a part of our official plans -- we're always open to collaborating with community members on something like this.  The agent communicates with APM Server via [an abstracted client](https://github.com/elastic/apm-nodejs-http-client/).  It's possible to build and swap out different client implementations. This means there is a relatively straightforward path if someone to wants to implement a client that communicates with something other than APM Server.  If anyone's interested in doing that get in touch (below, or privately) and we'll get you pointed in the right direction and answer any questions you might have about getting started.

**Comment by ebuildy** [comment]
We are not running APM in "big prod" yet, but this is the plan.

In dev, we use all the elasticAPM stack (from client to server), without any trouble. But I am remember in my experience with instrumentation/logging, performance issues because TCP (even with very low timeout).

I prefer to have a plan B , keep application code and replace only server backend, thats why I am asking.
