### ISSUE TITLE
elastic-apm-node hitting server request again and again

### ISSUE THREAD

**Issue by piyushmittal20** [elastic/apm-agent-nodejs#2182]
#### As you can see in my APM dashboard, I made only two hit:-

![image](https://user-images.githubusercontent.com/61026006/128508408-145ed56d-7109-4119-a026-7a20c0a5d550.png)
#### And In my discover there is already 55 hits:-

![image](https://user-images.githubusercontent.com/61026006/128508297-60f16287-8777-4f46-a828-83587c78b950.png)

**I dont't know like what is the issue going on, I am sharing my elastic-apm-node configuration code:**
```
const apm = require("elastic-apm-node").start({
  serviceName: "nodeAPMSerivce",
  serverUrl: "http://localhost:8200",
});

const express = require("express");
const connectDB = require("./config/db");
const dotenv = require("dotenv");
const User = require("./models/userModel");

dotenv.config();

const app = express();

connectDB();

app.use(express.json());

app.get("/", (req, res) => {
  res.send("Hey, I'm here!!");
});

app.get("/users", async (req, res) => {
  try {
    const users = await User.find({});

    res.status(200).json({
      users,
    });
  } catch (err) {
    console.log(err);
  }
});

app.post("/user", async (req, res) => {
  try {
    const savedUser = await User.create({ ...req.body });

    res.status(201).json({
      savedUser,
    });
  } catch (err) {
    console.log(err);
  }
});

app.listen(8080, () => {
  console.log("Hello I'm listening on PORT 8080");
});
```
If anyone know what is the issue or Is there anything in the code that I am missing please tell it to me.

@watson @Qard

**Comment by astorm** [comment]
Hey there @piyushmittal20, nice to meet you.  Qard and watson are on different teams these days, (their feedback's always welcome, but not required or expected), but we're happy to help you figure out what's going on. 

If I understand you correctly, I don't think what you want to do is recommended.  It's not how APM or Kibana are designed. So I'll explain what I mean by that, and then I'll give you a tool to might let you do what you want even if it's not recommended. 

Transactions arn't "hits".  A transaction groups together a bunch of work -- transactions are most commonly used to group together the work done to process the request for a single URL in a web application.

Because applications can have hundreds -- or even thousands -- of URLs, APM products (not just Elastic's) don't take a "one URL == one transaction" approach, (or to use your terminology, they're don't take a "one hit == one URL" approach).  That would quickly explode the user interface and also create a bunch of backend perf. issues to sort out.  

Instead we use the same grouping of URLs in your application's routing configuration.  If a user requests

```
http://localhost:8080/users
```

_in your application_ -- we get a transaction named `GET /users`.

So looking at your APM screenshots, **for the time period you have selected**, users have

1. Requested the `http://localhost:8080/users` URL

2. `POST`ed to a URL that's _not_ configured and gotten a 404 (the `POST unknown route` entry)

So -- that's just how APM works across the industry. 

However -- _if_ you really want to try giving each "hit" a unique transaction name for your locally running elasticsearch/kibana instance, [the setTransactionName](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-set-transaction-name) API will let you change the transaction name dynamically.  

Finally -- if you want to learn more about how things works in these projects [our community forums](https://discuss.elastic.co/) are probably a better place than GitHub issues. There you can get your issue in front of way more eyes than over here.  In the issues we try to stay focused on the bug and features related specifically to the agents. 

I'm going to close this one out but if you have additional questions or we've misunderstood your request please let us know.

**Comment by piyushmittal20** [comment]
Hey @astorm thanks for the answer but as you can see in the second screenshot that there are 55 hits and I hit my APIs only two times. So, that hitting after every 30 seconds is a bad thing or Is it necessary to stop it. And Can you please share any article or tutorial regarding the best practice for implementing this APM using Nodejs.

**Comment by Qard** [comment]
The transaction list is not individual requests, it's groupings of similar requests. One GET /users line could represent any number of requests and will present stats showing the average performance of that particular route grouping.

**Comment by astorm** [comment]
> that there are 55 hits and I hit my APIs only two times
> ....
> So, that hitting after every 30 seconds is a bad thing or Is it necessary to stop it

I've afraid I don't understand your concern here.  I'm going to describe what I see, and then ask you [to move this conversation over to the forums](https://discuss.elastic.co/).  We'd be happy to continue it over there, but these questions are outside the scope of the Node.js agent. 

Re: learning resources for APM -- there's [our general docs](https://www.elastic.co/guide/en/apm/get-started/current/index.html), our [Node.js agent](https://www.elastic.co/guide/en/apm/agent/nodejs/current/index.html) specific docs, and we also have [a number of observability trainings](https://www.elastic.co/training/).

The discover tab is showing you _every_ document in your elastic search instance (or every document for the index you have selected -- you don't have the index showing in your screenshot)

For every request made to your application an APM agent can create numerous documents in your elastic instance.  A Transaction is a single document.  Every transaction can have multiple spans -- each Span is a document.  Agents also report metrics -- these are documents.  Agents also report errors -- these are documents.  An elastic search instance also performs tasks unrelated to APM and may be inserting documents. 

The agent has a few configuration variables that can control the amount of data sent -- but keep in mind that less data means less information about what your system is doing.

- [`transactionSampleRate`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#transaction-sample-rate)

- [`metricsInterval`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#metrics-interval)

- [`metricsLimit`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#metrics-limit)

- [`breakdownMetrics`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#breakdown-metrics) 

When you open your conversation in the forum if you can let everyone know

1. What indexes you're viewing
2. And why you think 55 documents is too many (if that is what you think)

that will [help drive the conversation over there](https://discuss.elastic.co/).
