### ISSUE TITLE
bug: transaction.setDefaultNameFromRequest relies on instrumentation being loaded

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2288]
This  issue [comes from a discuss forum post](https://discuss.elastic.co/t/apm-and-koa-unknown-route/281228/11).

The following program

```
const apm = require('elastic-apm-node').start({
    serverUrl: 'http://some-apm-server',
    active: true,
    instrument: false,
    logLevel: 'trace',
});

const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router();

router.get('/', (ctx, next) => {
    ctx.body = 'hello world';
});

app
    .use(router.routes())
    .use(router.allowedMethods());

app.listen(3000);
```

Will produce a transaction name of `GET unknown route` when handling the root URL, despite that URL having a configured route. 

    $ curl http://localhost:3000/
    
We would expect a transaction name of `GET /`

## Root Cause

This bug occurs when the following configuration value is set

```
    instrument: false
```

which disables automatic instrumentation.

There's a bug in the `setDefaultNameFromRequest` method of the transaction object.  It uses the `getPathFromRequest` from the `./express-utils` module to fetch a request path if no `route` property is found.  If it can't fetch a request path, [it assumes an unknown route](https://github.com/elastic/apm-agent-nodejs/blob/c743e2bb8ff3dd31fbfef291ad2b3f33c3019985/lib/instrumentation/transaction.js#L210). 

The `getPathFromRequest` method _relies on our express instrumentation being loaded_. Specifically, the agent [grabs a path value using the `symbols.expressMountStack` symbol](https://github.com/elastic/apm-agent-nodejs/blob/c743e2bb8ff3dd31fbfef291ad2b3f33c3019985/lib/instrumentation/express-utils.js#L33) that our instrumentation sets on the request object.  

Additionally, the agent does not reach the `setDefaultNameFromRequest` code path when the `instrumentation` configuration value is set to `true`, as the KOA instrumentation will have already called `setDefaultTransactionName`. 

The `setDefaultNameFromRequest` (probably?) should not _rely_ on this symbol being set as `setDefaultNameFromRequest` is part of our generic HTTP instrumentation.  

Additional Info: PR where `instrument` configuration's current behavior landed: https://github.com/elastic/apm-agent-nodejs/pull/1114

**Comment by astorm** [comment]
## Disabling Instrumentation Configuration

There are three configuration variables that control instrumentation in the agent. 

### instrumentation

The agent uses the `instrumentation` configuration value to set the `enabled` boolean for an instrumentation module.  It does not control the patching of Node.js modules or the loading of instrumentations based on those modules.  It is up to each individual instrumentation module to obey the `enabled` boolean.  

Agent Reference Points: 

- https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/index.js#L186

### disableInstrumentation

The `disableInstrumentation` configuration value serves a similar function to the `instrumentation` configuration.  It's used to create a list of specific modules that a user wants to disable, and the agent uses this information to control the enabled/disable configuration send to individual instrumentation modules.  It does not control the patching of Node.js modules ot the loading of instrumentation based on those modules.  It is up to each individual instrumentation module to obey the `enabled` boolean.

Agent Reference Points:

- https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/index.js#L181-L186

### instrumentIncomingHTTPRequests

The `instrumentIncomingHTTPRequests` configuration controls whether the `http`, `https`, and `http2` modules will be wrapped in order to start transactions (and parse trace context headers) for individual HTTP requests.

This configuration is checked in individual instrumentation modules _before_ the `enabled` boolean is checked. 

Agent Reference Points

- https://github.com/elastic/apm-agent-nodejs/blob/666092ce517d14ef47e808160b4430b29c8fbb4b/lib/instrumentation/modules/http.js#L11

- https://github.com/elastic/apm-agent-nodejs/blob/666092ce517d14ef47e808160b4430b29c8fbb4b/lib/instrumentation/modules/https.js#L9

- https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/http2.js#L18

## Removing instrumentIncomingHTTPRequests

Question: Will removing the `instrumentIncomingHTTPRequests` configuration and combing it with `instrumentation` and `disableInstrumentation` effect Node.js async context tracking?

Answer: Slightly.  If users start transactions via `agent.startTransaction`, the `currentTransaction` value will still be set.  However, if they don't, this value will never be set.  Without a current transaction spans won't be created and most of the data an agent collects won't be sent to APM Server.  Additionally, trancecontext headers won't be parsed and the server will not show up as part of a distributed trace. 

Question: Is removing the `instrumentIncomingHTTPRequests` configuration a breaking change?

Answer: Soft yes on this.  For users who have never set any of the above three configuration variables, there will be no changed agent behavior.  However, if they _have_ set any of the above there may be subtle, unexpected changes to agent behavior based on the presense or non presense of a transaction.  

I'm softly opposed to changing this behavior without a major version bump.

**Comment by trentm** [comment]
`instrumentIncomingHTTPRequests` was added (#434, pull #1298) in v3.0.0 as a breaking change, with this justification:

> It's not possible to switch off the automatic creation of HTTP request transactions when an incoming HTTP request is detected without also switching off tracing of outgoing HTTP requests. 
> It would be very useful - both to users, but especially also during debugging - if it was possible to control the two features separately.

* * *

I re-read the [discuss thread](https://discuss.elastic.co/t/apm-and-koa-unknown-route/281228) and:

1. It sounds like adding a comment to [the Node.js agent's docs on `instrument`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#instrument) saying that `instrumentIncomingHTTPRequests` must also be set false to totally disable instrumentation would have been [helpful for the user in that discussion thread](https://discuss.elastic.co/t/apm-and-koa-unknown-route/281228/19).

2. It wasn't entirely clear to me if the user still wants the "WIP" to have the agent work hard to set a "default transaction name". The original post said:

> The problem is that even if I give a transaction name with transaction.name, APM tries to get the name from the koa-router. It's there any way to avoid this behavior?

If they *do* set `transaction.name` (which sets the internal `transaction._customName`, then that value will get used over whatever value is determined for the "default" transaction name.

3. Perhaps it was confusion over requests to other endpoints -- like the point Alan made about a request from the browser for "GET /favicon.ico"?  I.e. the user is getting `GET unknown root` transaction names on service endpoints that they happen to *not* be explicitly setting a custom name via `transaction.name = "custom name"`. If so, could we suggest the user use [`usePathAsTransactionName`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#use-path-as-transaction-name) and *not* add [Alan's WIP](https://github.com/elastic/apm-agent-nodejs/pull/2299)

We should likely also improve the Node.js agent's docs on this config option to include [the warning about possible explosion of transaction groups that the Java equivalent mentions](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-use-path-as-transaction-name).

4. On the "instrument:false for Node.js is inconsistent with other agents" question: I think one option is to consider it a **bug** that `instrument:false` doesn't also disable incoming http request instrumentation. When `instrumentIncomingHTTPRequests` was added the intent was to have separate control from `disableInstrumentations=http,...`. I don't think the intent was to have separate control from `instrument:false` -- I think it ws just missed, because where `  if (agent._conf.instrumentIncomingHTTPRequests) {` is checked the `enabled` boolean has already been calculated from `conf.disableInstrumentations` and `conf.instrument`

https://github.com/elastic/apm-agent-nodejs/blob/666092ce517d14ef47e808160b4430b29c8fbb4b/lib/instrumentation/modules/http.js#L10-L19

Changing those guards to `  if (agent._conf.instrumentIncomingHTTPRequests && agent._conf.instrument) {` would do it.

**Comment by astorm** [comment]
Consider the following small program

    const apm = require('elastic-apm-node').start({
      serverUrl: 'http://some-apm-server',
      active: true,
      instrument: false,
      logLevel: 'trace',
    });

    const Koa = require('koa');
    const Router = require('koa-router');

    const app = new Koa();
    const router = new Router();

    router.get('/hello', (ctx, next) => {
      apm.setTransactionName('this is a test')
      ctx.body = 'hello world';
    });

    app
      .use(router.routes())
      .use(router.allowedMethods());

    app.listen(3000);

When running this program we're able to rename the current transaction successfully despite the default transaction name being set to unknown.

Similarly, the following program is able to start a transaction with a default name and set a custom name.

    const apm = require('elastic-apm-node').start({
      serverUrl: 'http://some-apm-server',
      active: true,
      instrument: false,
      logLevel: 'trace',
      instrumentIncomingHTTPRequests: false,
    });

    const Koa = require('koa');
    const Router = require('koa-router');

    const app = new Koa();
    const router = new Router();

    router.get('/hello', (ctx, next) => {
      apm.startTransaction('this is my transaction');
      // apm.setTransactionName('uncomment to set custom name')
      ctx.body = 'hello world';
      apm.endTransaction();
    });

    app
      .use(router.routes())
      .use(router.allowedMethods());

    app.listen(3000);

This appears to cover the expected use cases [from the original discuss forum post](https://discuss.elastic.co/t/apm-and-koa-unknown-route/281228/11), and that the WIP PR isn't needed.  We'll be closing this issue for now, but if anyone has trouble with custom transaction naming when these configuration values are in use please let us know.
