### ISSUE TITLE
Throw errors instead of logging to stdout

### ISSUE THREAD

**Issue by Ionaru** [elastic/apm-agent-nodejs#232]
Snippet from my nodejs log:
```
2018-02-07 11:07:23 - info: Config loaded: 'marketbot.ini'
Elastic APM isn't correctly configured: Missing serviceName
2018-02-07 11:07:23 - info: Elastic APM enabled, logging to 'http://localhost:8200'
2018-02-07 11:07:23 - info: Starting bot activation
```
Elastic APM is started with this:
```typescript
elastic.start({
  appName: 'marketbot',
  secretToken: configuration.getProperty('elastic.token'),
  serverUrl: configuration.getProperty('elastic.url')
});
```

If Elastic APM cannot start because of some reason (for example an error in configuration), I expect to get an error. Instead the module logs directly to stdout, bypassing my custom logger.

I'd like Elastic APM to throw errors instead of logging to stdout, this way I can choose to react to the error, do nothing or let the application crash.

The same behaviour happens when calling `transaction.end();`. If the request fails then I expect an error here as well.

Instead of this output:
```
Error: connect ECONNREFUSED 127.0.0.1:8200
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
```

**Comment by watson** [comment]
Thanks for raising this issue @Ionaru 

Before addressing the issue and in case you hadn't seen it, I just want to mention that it's possible to supply a custom logger using the [`logger`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#logger) config option. If none is provided the agent will default to use stdout or stderr as you saw.

As a principle we do not throw if errors occur so that the agent does not impact the stability the application being instrumented. That being said, we could probably improve our current implementation in a few ways:

1. Today, even when a custom logger is used, we do not supply the original error object to the logger. Instead we pass on either the error message or the stack trace in the form of a string. Some loggers handle error objects in special ways, so it would be beneficial to support this.
1. While it's normally unwise for Node modules to throw during operation, it's not uncommon to throw if they are called with invalid arguments. It might make sense to apply this pattern to the `start()` function, so if called without the required arguments, it would throw.

I'd love your feedback on these suggestions and any others you might have that can improve the experience of handling errors and logging in general 😃

Regarding the specific errors you encountered:

- The `appName` property have been renamed `serviceName` in version 1.0.0. I'll make sure we publish a proper upgrade guide ASAP. In the meantime you can check [CHANGELOG.md](https://github.com/elastic/apm-agent-nodejs/blob/master/CHANGELOG.md#100---201826) for a list of changes
- While in development, you normally don't run the APM Server along side your application. To avoid the agent from trying access the server and failing (which results in the `ECONNREFUSED` error you posted above), I usually set the [`active`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#active) property to `false` while running locally

**Comment by dicarlo2** [comment]
@watson Am I missing something? I've tried setting the `logger` option but it doesn't seem to do anything. Looking at the code, it's not clear to me that it should: https://github.com/elastic/apm-agent-nodejs/blob/master/lib/logger.js

**Comment by dicarlo2** [comment]
https://github.com/elastic/apm-agent-nodejs/commit/98cfaa218f60085e6c79518c9588c3d9d0f83d95 looks like this commit removed the ability to use a custom logger.

**Comment by watson** [comment]
@dicarlo2 Thanks for raising this. I've created an issue on it: #289

**Comment by astorm** [comment]
Coming back to this a few years later, it looks like our customer logger was fixed, so that aspect of this issue is completed. 

Re:

> I'd like Elastic APM to throw errors instead of logging to stdout, this way I can choose to react to the error, do nothing or let the application crash.

Speaking broadly the agent goes out of its way _not_ to throw an exception that might not be caught. We do this out of an abundance of caution for not crashing the application under instrumentation. 

Closing this out for now, but we're always happy to revisit here in old 2020.
