### ISSUE TITLE
How to group transactions by operation name for a graphql endpoint

### ISSUE THREAD

**Issue by toxsick** [elastic/apm-agent-nodejs#2424]
**Describe the issue**

Hey guys,

I am just getting started with elastic apm and I have a beginner question regarding a graphql endpoint. I am using an express server with `express-graphql@0.12.0`. I'm getting traces as expected:

![Transactions | server | Services | APM 2021-11-08 16-03-11](https://user-images.githubusercontent.com/951466/140765917-91486efd-7ae1-460d-a7e2-e3cef2579621.png)

![graphql - Transactions - server - Services - APM - Observability - Elastic 2021-11-08 16-05-45](https://user-images.githubusercontent.com/951466/140766636-b61f38ec-853b-4f31-9b82-2cd0b36cb714.png)

My problem is that all calls to the `/graphql` endpoint are combined as only one transaction. This does not make sense, since individual graphql queries have very different performance characteristics. The desired behaviour would be to get one transaction per graphql query by query / operation name (the next level in the screenshot above). This is also described in the elastic apm spec here:

https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-graphql.md

What do I have to change to get individual transactions for different graphql queries?

**Environment (please complete the following information)**

- OS: Alpine Linux
- Node.js version: 14.15.1
- APM Server version: 7.15.1
- Agent version: 3.23.0 (elastic-apm-node)

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`
- [x] Starting node with `-r ./elastic-apm-shim.js`

```js
// elastic-apm-shim.js

const apm = require('elastic-apm-node').start({
  serviceName: 'server',
  serverUrl: 'http://localhost:8200',
});
```
Thanks and best regards

Hannes

**Comment by trentm** [comment]
@toxsick Thanks for the issue, and sorry for the delay in responding. 

I went down the rabbit hole of trying to understand why I was seeing a differentiated transaction.name:
<img width="899" alt="Screen Shot 2021-12-08 at 1 12 23 PM" src="https://user-images.githubusercontent.com/46866/145285112-1e228ad6-402c-4f6b-943b-77c4c0cd3c53.png">

and you weren't.

Almost certainly this is because our instrumentation for express-graphql explicitly doesn't instrument versions `>0.9.0` currently. I [noticed this yesterday](https://github.com/elastic/apm-agent-nodejs/issues/2507).

My play example is using `express-graphql@0.9.0`:

```
% npm ls express-graphql
elastic-apm-node@3.26.0 /Users/trentm/el/apm-agent-nodejs
└── express-graphql@0.9.0
```

and yours is `express-graphql@0.12.0`.


It looks like the express-graphql library has changed enough that the APM agent's instrumentation has to change somewhat. My play example:

```js
// play-express-graphql.js
require('.').start({
  serviceName: 'play-express-graphql',
  logUncaughtExceptions: true
})

var graphql = require('graphql')
var express = require('express')
var graphqlHTTP = require('express-graphql')

var schema = graphql.buildSchema('type Query { hello: String }')
var root = {
  hello () {
    return 'Hello world!'
  }
}

var app = express()
app.use('/graphql', graphqlHTTP({ schema: schema, rootValue: root }))
app.listen(3000, function () {
  console.warn('listening on http://localhost:3000')
})
```

Fails with `express-graphql@0.12.0`:

```
% node play-express-graphql.js
TypeError: graphqlHTTP is not a function
    at Object.<anonymous> (/Users/trentm/el/apm-agent-nodejs/play-express-graphql.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
{"log.level":"info","@timestamp":"2021-12-08T21:18:37.974Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Sending error to Elastic APM: {\"id\":\"fadc0461a839f4beaa7628c0c35c382f\"}"}
```

If you are familiar with express-graphql, a PR to update our [express-graphql instrumentation](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/express-graphql.js) would be very welcome.

**Comment by trentm** [comment]
I should have a fix with https://github.com/elastic/apm-agent-nodejs/pull/2511

**Comment by trentm** [comment]
@toxsick Thanks for getting back. I expect to have a release early next week (or possibly sooner) to get this fix and a coming unrelated change.

**Comment by toxsick** [comment]
Perfect, thank you very much!

**Comment by trentm** [comment]
@toxsick elastic-apm-node@3.27.0 is now released with this fix.

**Comment by toxsick** [comment]
Super nice, thanks a lot!
