### ISSUE TITLE
Only 30 tests are reported when running in the CI

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-nodejs#2443]
**Describe the bug**

We have noticed that since https://github.com/elastic/apm-agent-nodejs/pull/2138 the main pipeline of the APM Agent Node.js is reporting only 30 tests to the CI, before of that change it was reporting about few thousands of tests.

![image](https://user-images.githubusercontent.com/2871786/141962586-0098dfd5-d9a2-4e3c-bb88-99abac593129.png)

**Expected behavior**

The CI reports the executed tests as expected, this will help with all the notifications, flaky tests analyser and other bits and pieces we have automated.

For instance, before the above changes then the number of tests reported in the CI can be seen below

![image](https://user-images.githubusercontent.com/2871786/141962916-ac939f19-8f2c-4c60-b34e-c3cd6bc37120.png)

https://github.com/elastic/apm-agent-nodejs/pull/2094#issuecomment-851672524

**Comment by trentm** [comment]
I don't see how this could be associated with the changes from #2138.

@v1v Am I right that the Jenkins "Test Results" is a representation of the junit XML file created from https://github.com/elastic/apm-agent-nodejs/blob/bf760484ad80a2a26fb5f46a9795f2e5145b94c5/.ci/Jenkinsfile#L374 ?

Is there a way to have these `*-junit.xml` be build artifacts so we can look at them?

For what it is worth, I tried to mimic what `tap2Junit.groovy` is doing, using a "test-suite-output.tap" test result output file that I had kicking around in my dev area (https://gist.github.com/trentm/d0e56068ff614f07c1977d6cd9b09248) using this bash:

```bash
set -e
set -x
docker run --rm \
    -v $(pwd):/usr/src/app \
    -w /usr/src/app \
    node:12-alpine \
    sh -c 'export HOME=/tmp ; mkdir ~/.npm-global; npm config set prefix ~/.npm-global ; npm install tap-xunit -g ; for i in "*-output.tap" ; do echo "i is $i"; ls ${i}; cat ${i} | /tmp/.npm-global/bin/tap-xunit --package="Node.js" > ${i%.*}-junit.xml ; done'
```

I added `echo "i is $i"; ls ${i}; ` to try to see what was going on in there.
I don't know if I have the quoting correct, but this is the result I got:

```
% bash foo.sh
++ pwd
+ docker run --rm -v /Users/trentm/el/apm-agent-nodejs:/usr/src/app -w /usr/src/app node:12-alpine sh -c 'export HOME=/tmp ; mkdir ~/.npm-global; npm config set prefix ~/.npm-global ; npm install tap-xunit -g ; for i in "*-output.tap" ; do echo "i is $i"; ls ${i}; cat ${i} | /tmp/.npm-global/bin/tap-xunit --package="Node.js" > ${i%.*}-junit.xml ; done'
/tmp/.npm-global/bin/tap-xunit -> /tmp/.npm-global/lib/node_modules/tap-xunit/bin/tap-xunit
/tmp/.npm-global/bin/txunit -> /tmp/.npm-global/lib/node_modules/tap-xunit/bin/tap-xunit
+ tap-xunit@2.4.1
added 21 packages from 21 contributors in 2.124s
i is *-output.tap
test-suite-output.tap
```

and it created a `*-output-junit.xml` (with a literal asterisk in it), which seems surprising. Here is that junit xml file: https://gist.github.com/trentm/8d769158337a557294bb7bf15cf45ee0

It looks to me like that 'tap-xunit' conversion is generating a single `<testcase>` for that whole file, which seems wrong.

**Comment by v1v** [comment]
> @v1v Am I right that the Jenkins "Test Results" is a representation of the junit XML file created from

Yes

> Is there a way to have these *-junit.xml be build artifacts so we can look at them?

Yes, in the pipeline itself it's possible to add the `archiveArtifacts '*-junit.xml'`

Regarding `tap2Junit.groovy`, it uses the latest version `tap-xunit`. There are a couple of questions here:
- Either the `tap-xunit` has changed recently
- Or the consumer, aka the pipeline, does not produce the required files in the required format to be consumed by `tap2Junit`

At least, that's what I see so far.

I'll enable the archive for `*-output.tap` and `*-junit.xml` and see whether the expected files are created correctly.

**Comment by v1v** [comment]
I see the issue is not with `tap2Junit` but the TAP output contract has changed. 

See [here](https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/PR-2449/1/artifact/test-suite-output.tap/*view*/)

The script in charge to run TAP and create the TAP output file has changed and the file contains all the TAP executions:

```
running (cwd: ./test/start/env): node --require /app/test/_promise_rejection.js test.test.js
TAP version 13
# from-env service name test
ok 1 should be strictly equal

1..1
# tests 1
# pass  1

# ok

running (cwd: ./test/start/file): node --require /app/test/_promise_rejection.js test.test.js
TAP version 13
# from-file serviceName test
ok 1 should be strictly equal

1..1
# tests 1
# pass  1
```

As far as I see `test-suite-output.tap` is generated by https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/scripts/docker-test.sh#L60 that uses https://github.com/elastic/apm-agent-nodejs/blob/master/test/test.js


I'm now trying with https://github.com/elastic/apm-agent-nodejs/pull/2450 to see if reverting a particular commit how it goes

**Comment by v1v** [comment]
I managed to find when things started:

- https://github.com/elastic/apm-agent-nodejs/runs/3001901586 is the very last github check with the 19.000 reported tests.

![image](https://user-images.githubusercontent.com/2871786/142197295-88b59655-5f2d-4c33-92e3-e190f75819cc.png)

- https://github.com/elastic/apm-agent-nodejs/runs/3003446829 is the very first github check with only 20 reported tests

![image](https://user-images.githubusercontent.com/2871786/142197390-5c5ac942-2937-4fc7-81f2-4c7ce41b78c8.png)

Therefore as commented above everything started with https://github.com/elastic/apm-agent-nodejs/commit/6fa6f952740930ef6570468e44233397d0f14492

**Comment by trentm** [comment]
# current master

Using latest master with the following diff to reduce the number of tests run (just to be faster):

```diff
diff --git a/package.json b/package.json
index c9db6362..b9e0f9a7 100644
--- a/package.json
+++ b/package.json
@@ -109,6 +109,7 @@
     "set-cookie-serde": "^1.0.0",
     "shallow-clone-shim": "^2.0.0",
     "sql-summary": "^1.0.1",
+    "tap-xunit": "^2.4.1",
     "traceparent": "^1.0.0",
     "traverse": "^0.6.6",
     "unicode-byte-truncate": "^1.0.0"
diff --git a/test/test.js b/test/test.js
index 7dff126d..c6689628 100644
--- a/test/test.js
+++ b/test/test.js
@@ -71,6 +71,7 @@ function mapSeries (tasks, handler, cb) {
 }

 var directories = [
+  /*
   'test',
   'test/cloud-metadata',
   'test/instrumentation',
@@ -98,6 +99,7 @@ var directories = [
   'test/sanitize-field-names',
   'test/sourcemaps',
   'test/stacktraces',
+  */
   'test/uncaught-exceptions'
 ]
```

and running this (which is the equivalent of [what the Jenkins tests are running](https://github.com/elastic/apm-agent-nodejs/blob/d716d57adc133528ca9aa747142808f9bf1711bf/.ci/scripts/docker-test.sh#L60)):

```
npx nyc node test/test.js | tee test-suite-output.tap
```

Yields this "test-suite-output.tap":
https://gist.github.com/trentm/ef725cf4a65d558b3eca05f72c4490a3

Processing that with tap-xunit [the way apm-pipeline-library `tap2Junit` is doing](https://github.com/elastic/apm-pipeline-library/blob/master/vars/tap2Junit.groovy#L43) results in just a single `<testcase>`, which is the XML tag that I think Jenkins's "Test Results" view is counting:

```
% cat test-suite-output.tap| ./node_modules/.bin/tap-xunit | rg '<test'
<testsuites>
  <testsuite tests="1" failures="0" errors="0" name="from-env service name test">
    <testcase name="#1 should be strictly equal">
```

# before https://github.com/elastic/apm-agent-nodejs/pull/2138

```
$ git stash
$ git checkout 69d1dfbe9e0722ffaaf82b72735b9d2952b6f6c2
$ git stash pop  # restore our diff from above
```

Running (a subset of) the tests again:

```
npx nyc node test/test.js | tee test-suite-output.tap
```

Yields this "test-suite-output.tap":
https://gist.github.com/trentm/de2bc7895a9f9ae79124f9b2259362da


And tap-xunit seems happier with this .tap file:

```
% cat test-suite-output.tap| ./node_modules/.bin/tap-xunit | rg '<test'
<testsuites>
  <testsuite tests="7" failures="0" errors="0" name="should capture uncaught exceptions but not log if disabled">
    <testcase name="#1 should capture the error"/>
    <testcase name="#2 error.exception.message"/>
    <testcase name="#3 error.exception.type"/>
    <testcase name="#4 error.exception.handled"/>
    <testcase name="#5 should have a stack trace"/>
    <testcase name="#6 stack trace should contain frames"/>
    <testcase name="#7 top frame should be this file">
```

Happi*er*, but still not correct. Note that the "test-suite-output.tap" above has:

```tap
# ...
TAP version 13
# ...

1..7

# ...
TAP version 13
# ...

1..8
# ...
```

If we care about a full count of all test cases from this TAP output, we would
expect a count of *15* here, but we only got *7*.

# both are broken

I believe that `tap-xunit` is only processing up to the first `N..M` tap marker.

For the first case above (latest master) the first `N..M` marker is `1..1` from running "./test/start/env/test.test.js". This changed in https://github.com/elastic/apm-agent-nodejs/pull/2138 here:
- before: https://github.com/elastic/apm-agent-nodejs/commit/6fa6f952740930ef6570468e44233397d0f14492#diff-def89e9301811423d384b95ba9e50666dd4d7e1bcc9699a05ea72e03a6e8fb49

    ```
    running (cwd: ./test/start/env): node --unhandled-rejections=strict test.js
    ```

- after: https://github.com/elastic/apm-agent-nodejs/commit/6fa6f952740930ef6570468e44233397d0f14492#diff-11c94d94b4a8647075d4da18d47382ff76b475bb228256f8079e426dbf6bd34d

    ```
    running (cwd: ./test/start/env): node --unhandled-rejections=strict test.test.js
    TAP version 13
    # from-env service name test
    ok 1 should be strictly equal

    1..1
    # tests 1
    # pass  1

    # ok
    ```

This is why the count for each "test-suite-output.tap" file dropped to *1*.
If I run the test suite without my diff above, then the first `N..M` marker used
to be `1..853` from running "test/agent.js".  ~850 times the number of test
steps in the matrix (~20):

```
>>> 853 * 20
17060
```

That answers why the number of "Test Results" dropped from ~17k to ~20.

# the issue

The bug is that "test-suite-output.tap" is not proper TAP output. From https://testanything.org/tap-version-13-specification.html#the-plan (emphasis mine):

> The plan tells how many tests will be run, or how many tests have run. It’s a check that the test file hasn’t stopped prematurely. **It must appear once, whether at the beginning or end of the output.**


This repos "test/test.js" is concatenating TAP output from separate executions of each test file, which technically isn't valid TAP, so it isn't `tap-xunit`'s fault that it is misparsing it.

# solutions

## solution option 1: switch to `tap` runner

I'd started an effort a while back to switch from our "test/test.js that
executes `tape test/path/to/foo.test.js` for each file" current test running to
"run `tap test/**/*.test.js`": https://github.com/elastic/apm-agent-nodejs/tree/trentm/tap
However, that is now out of date and it is a significant effort to get there, so
it will likely be a while.

Even if we got there, here is a taste of what this would mean for Jenkins "Test Results".
Running just a subset of tests with tap for a smaller sample:

```
% TAP=1 ./node_modules/.bin/tap test/uncaught-exceptions/*.js | tee tap-output.tap
TAP version 13
Error: foo
    at Test.<anonymous> (/Users/trentm/el/apm-agent-nodejs/test/uncaught-exceptions/log-uncaught-exceptions-on.js:43:23)
    at Test.bound [as _cb] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:96:32)
    at Test.run (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:114:31)
    at Test.bound [as run] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:96:32)
    at Immediate.next (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/results.js:88:19)
    at processImmediate (internal/timers.js:461:21)
    at process.callbackTrampoline (internal/async_hooks.js:126:14)
ok 1 - test/uncaught-exceptions/log-uncaught-exceptions-off.js # time=365.926ms {
    # should capture uncaught exceptions but not log if disabled
    ok 1 should capture the error
    {"log.level":"info","@timestamp":"2021-11-17T20:01:05.482Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Sending error to Elastic APM: {\"id\":\"656379b99cf587919f02d99468fc560b\"}"}
    ok 2 error.exception.message
    ok 3 error.exception.type
    ok 4 error.exception.handled
    ok 5 should have a stack trace
    ok 6 stack trace should contain frames
    ok 7 top frame should be this file

    1..7
    # tests 7
    # pass  7

    # ok
}

ok 2 - test/uncaught-exceptions/log-uncaught-exceptions-on.js # time=367.805ms {
    # should capture and log uncaught exceptions by default
    ok 1 should log the error to STDERR
    ok 2 should capture the error
    {"log.level":"info","@timestamp":"2021-11-17T20:01:05.484Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Sending error to Elastic APM: {\"id\":\"80d3eae9e6d4bf01dc690953e5879b36\"}"}
    ok 3 should be strictly equal
    ok 4 should be strictly equal
    ok 5 should be strictly equal
    ok 6 should have a stack trace
    ok 7 stack trace should contain frames
    ok 8 top frame should be this file

    1..8
    # tests 8
    # pass  8

    # ok
}

1..2
# time=378.465ms
```

and attempting to convert that with `tap-xunit` results in:

```
% cat tap-output.tap | ./node_modules/.bin/tap-xunit
<?xml version="1.0"?>
<testsuites>
  <testsuite tests="1" failures="0" errors="0" name="Default">
    <testcase name="#1 test/uncaught-exceptions/log-uncaught-exceptions-off.js # time=365.926ms {"/>
  </testsuite>
  <testsuite tests="0" failures="0" errors="0" name="# should capture uncaught exceptions but not log if disabled"/>
  <testsuite tests="0" failures="0" errors="0" name="# tests 7"/>
  <testsuite tests="0" failures="0" errors="0" name="# pass  7"/>
  <testsuite tests="1" failures="0" errors="0" name="# ok">
    <testcase name="#2 test/uncaught-exceptions/log-uncaught-exceptions-on.js # time=367.805ms {">
      <system-out>    ok 1 should log the error to STDERR
</system-out>
      <system-out>    ok 2 should capture the error
</system-out>
      <system-out>    {"log.level":"info","@timestamp":"2021-11-17T20:01:05.484Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"Sending error to Elastic APM: {\"id\":\"80d3eae9e6d4bf01dc690953e5879b36\"}"}
</system-out>
      <system-out>    ok 3 should be strictly equal
</system-out>
      <system-out>    ok 4 should be strictly equal
</system-out>
      <system-out>    ok 5 should be strictly equal
</system-out>
      <system-out>    ok 6 should have a stack trace
</system-out>
      <system-out>    ok 7 stack trace should contain frames
</system-out>
      <system-out>    ok 8 top frame should be this file
</system-out>
      <system-out>    1..8
</system-out>
      <system-out>}
</system-out>
    </testcase>
  </testsuite>
  <testsuite tests="0" failures="0" errors="0" name="# should capture and log uncaught exceptions by default"/>
  <testsuite tests="0" failures="0" errors="0" name="# tests 8"/>
  <testsuite tests="0" failures="0" errors="0" name="# pass  8"/>
  <testsuite tests="0" failures="0" errors="0" name="# ok"/>
</testsuites>
```

This results in *2* `<testcase>`s, which seems fine, but not the best. However
that output shows that it is struggling to interpret the generated TAP output from node-tap.
I'm not sure if the issue there is (a) node-tap generating TAP that isn't to spec, (b) tap-xunit limitations, or (c) the apm-agent-nodejs tests breaking test output rules.


## solution option 2: pre-process "test/test.js" output

We could pre-process "test-suite-output.tap" before passing to tap-xunit.
This strikes me as adding some complexity that isn't of great value.

## solution option 3: change "test/test.js" to make multiple .tap files

We could change "test/test.js" to write a .tap output from file *each* test
file. Then `tap-xunit` could be called for each to generate multiple junit files.


# How much does this matter?

How much does this matter? I don't *personally* get utility out of (a) the
count of "Test Results" or (b) any part of the "Test Results" display in
Jenkins for this repo. Do others?

**Comment by trentm** [comment]
>  I don't personally get utility out of ... "Test Results"

The only things I want out of the jenkins runs is:
1. Did the full test suite pass or fail?
2. If it failed, I want a visualizations of which parts of the test matrix failed. Currently the best for this is a combination of the "Stage View" (e.g. at https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/) and the "Blue Ocean" view of a particular build (e.g. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/1184/).
3. For each failing build "step" (each of nodes in the Blue Ocean graph), I want to see log output for either the full step, or for each command that is part of that "step". I use the Blue Ocean page to look at this. However, I find it a bit clunky.

**Comment by v1v** [comment]
Thanks @trentm for your throughout analysis.

From the homogeneous point of View, we want everyone at observability to have a similar development experience, therefore the CI is one of the key areas where the productivity can be increased if the output is meaningful and correctly presented.

This is not about a personal preference but an experience for every contributor. For instance, if I contribute to this repo and the CI does not report a test failure but a failure, then based on what we have in the other GitHub projects, I'll be drilling down in the logs to find if there was a compilation/runtime error. If I see a test failure, then I'd be concerned since it was not genuinely reported in the right UI. 

Therefore, test failures if they are reported correctly, there is a likely less chance to need to go to the logs or even the Jenkins UI (BlueOcean or traditional one). That's in fact, what we tried to do with the GitHub Comment that contains the build status. It might not be ideal or work for every one but we can make this more customised or adapt the different requirements.

On the other hand, we are working on applying observability to the CI/CD and test results is actually one of the areas we are working. If we don't transform to JUnit then we wont get for free all the things we are working on .

Regarding your questions:
> Did the full test suite pass or fail? 

If so, how likely we can discover flakiness? We cannot use any automation but ask the system owner if they know if the test is flaky. So from the onboarding PoV I think we need to make the most valua of the CI to provide insights and trends.

> If it failed

Then the GitHub comment/status should provide the step that failed with a link to the logs and the command that was executed.

> For each failing build "step"

See above.


To illustrate this, see https://github.com/elastic/apm-agent-nodejs/runs/4214868010 that contains the Build status.

![image](https://user-images.githubusercontent.com/2871786/142391380-5a9da295-7889-445e-8833-e91d772508ec.png)

As a team, we want to avoid, if possible, GitHub actions as much as possible to allow an homogenous and great experience for every single person who contributes to the Observability solution.


I hope I managed to provide an overview of the implications and the rationale of using the most of the capabilities the CI can provide in favour of a standardise and productive experience.


Regarding the solution 3 seems the one that won't require any other trick, `tap2Junit(pattern: '*-output.tap', suffix: 'junit.xml', package: 'Node.js', failNever: true) ` supports patterns so if the tool create those files and name them with the suffix `-output.tap` then everything will work nicely and easily :)

**Comment by trentm** [comment]
> If I see a test failure, then I'd be concerned since it was not genuinely reported in the right UI

I suppose. Perhaps my experience is different. I've never found the "Test Results" summary in Jenkins to be useful. It is a representation of the test run that, in general, is missing details like the full log output of the test run. Obviously I can't use this project as a fair comparison because its JUnit Test Results reporting has obviously been broken for a long time (perhaps for the entire time).


> > If it failed
> Then the GitHub comment/status should provide the step that failed with a link to the logs and the command that was executed.

Thanks. I had not been using that and it looks useful as a shortcut for getting to the log for a specific failed step.


> > Did the full test suite pass or fail?
> 
> If so, how likely we can discover flakiness? ...

Fair, in general. For *this repo*, I believe we've eliminated flaky tests. At least I have tried hard to stamp them out. The only current flaky one I know of currently is https://github.com/elastic/apm-agent-nodejs/issues/2409

Allowing flaky tests to exist in the repo and only be "handled" by downstream test reporting in Jenkins would drive me crazy. :) I want a local `make test` (or `npm test`) test run to pass for local dev.


> If we don't transform to JUnit then we wont get for free all the things we are working on .

One of these things is reporting on flaky tests, right? What are other things we hope to get out of JUnit test run analysis?



> As a team, we want to avoid, if possible, GitHub actions as much as possible ...

As a data point, the main reasons I appreciate the GH Actions we use on this repo for testing:

- Faster response time: The lint check responds in ~1m, the per-node-version test suite runs in ~8m:
![Screen Shot 2021-11-18 at 8 55 27 AM](https://user-images.githubusercontent.com/46866/142460898-065c5882-e85a-4e95-83ab-70c80b476831.png)
  The Jenkins tests take typically ~17m for the equivalent set of tests.
- A second opinion: When we get a failure in one system (GH actions, or jenkins) and not in the other, then we know the issue is likely environmental and not due to code changes.
- The integration of "checks" reporting in GitHub PR is much smoother with our GH actions, currently.


I realize that I'm being a little selfish (i.e. thinking only of this repo) in my answers above.  I appreciate our Jenkins CI and rely on it as the foundation for approving PRs/releases, for benchmarks, for the TAV test runs, for integration tests, etc.

**Comment by astorm** [comment]
Just dropping in to say it sounds like (re: the specific issue) "option 3: change 'test/test.js' to make multiple .tap files" is the one that's the best combination of expedience and correctness.  

Also, @v1v, I have a tangential question that might be impossible to answer, but above you mentioned

> I see the issue is not with tap2Junit but the TAP output contract has changed.

Are the expectations/contracts of the Jenkins CI Pipelines documented anywhere?  

I understand that there's a general elastic-wide use and value for these Jenkins based systems but we (the Node Agent team) also have to consider the tooling we need to get our jobs done in a reasonable amount of time and also what the average Node.js Open Source contributor is going to expect to find in the repository.  

In general I think the Jenkins/GitHubActions (previously Jenkins/Travis) split has been a reasonable compromise, but I'd be interesting in hearing your thoughts on which parts of the CI/CD that the robots team is responsible for and which parts the individual engineering team is responsible for, and what the contracts are that you need us to uphold.

Put another way -- what can we do to avoid similiar breaking changes that don't show up on anyone's radar for four months? ;)

**Comment by v1v** [comment]
> Fair, in general. For this repo, I believe we've eliminated flaky tests. At least I have tried hard to stamp them out. The only current flaky one I know of currently is #2409

That's great news, though generally speaking one of the problems for the flaky tests is the knowledge of the nature. Only the core contributors might have enough context/knowledge about this. But eventual contributors not.

That's the reason of one of the points I mentioned earlier about Observing the CI/CD. If Test results are reported by the CI then they can eventually be analysed automatically and provide further insights.

If any of the core contributors leave then this particular knowledge about the flaky test analysing is gone but if the automation is in place then it will remain.

> One of these things is reporting on flaky tests, right? What are other things we hope to get out of JUnit test run analysis?

I touched about this above, but in a nutshell, we have enabled integration for different tools to send distributed traces, those integrations are with Jenkins itself, Maven build system, Ansible, Pytest, JUnit  and more to come. All those integrations will provide an holistic overview of the CI/CD ecosystem.

There are obviously more information that could be gathered, such as, automatically report if a Test failure happened to the last person who touched, or any other kind of processes. By being able to gather those details and publish them in a normalise manner we will be in a position to build more automation in place.

Happy to talk further if you need.

> Are the expectations/contracts of the Jenkins CI Pipelines documented anywhere?

The only expectation to transform any TAP to JUnit is the TAP generated files should be compliance with the tap2junit npm library.

TAP is not a valid reporting tool to track the historical executions for the executed tests

Finally, we cannot warranty that every single build that run in the CI triggered all the tests, because there is no visualisation about what tests have been executed. The only way to know that it's going to the logs and look for the information. But logs remain for a period of time only.

All the assets regarding the tests are always sent to ElasticSearch when they run in the CI, therefore we can search for what tests were executed and what was the outcome. Then from the auditing point of view, we know what happen for every commit in this repository.

> I understand that there's a general elastic-wide use and value for these Jenkins based systems but we (the Node Agent team) also have to consider the tooling we need to get our jobs done in a reasonable amount of time and also what the average Node.js Open Source contributor is going to expect to find in the repository.


Sounds fine, though I mentioned earlier we are building a solution to observe the CI/CD with distributed traces, the more we can converge in the same solution the better. 

> In general I think the Jenkins/GitHubActions (previously Jenkins/Travis) split has been a reasonable compromise, but I'd be interesting in hearing your thoughts on which parts of the CI/CD that the robots team is responsible for and which parts the individual engineering team is responsible for, and what the contracts are that you need us to uphold.

Let me poke @cachedout

> Put another way -- what can we do to avoid similiar breaking changes that don't show up on anyone's radar for four months? ;)

Tests were until 4 months ago reported in the Build status, either in the Jenkins trend or the GitHub comment. Maybe, adding a checklist in the code review to ensure the number of shown tests are the expected ones?

To illustrate the above, see https://github.com/elastic/apm-agent-nodejs/issues/2443#issuecomment-971516488 or in the traditional Jenkins UI -> https://apm-ci.elastic.co/job/apm-agent-nodejs/job/apm-agent-nodejs-mbp/job/master/lastCompletedBuild/testReport/

**Comment by cachedout** [comment]
This thread has been an interesting read. I've enjoyed hearing all the different points of view. 

Apologies if my comments here veer too far away from the original issue. I don't mean to distract from the original report in this issue. I'll try to stay a few levels above specific implementation questions which have already been discussed, but am happy to dive deeper if needed.

> ...what the contracts are that you need us to uphold.

This is a very important question. The short answer here is that is the case with a lot of organic growth, we haven't explicitly set standards so much as we've come to converge toward what's been most common and then built solutions on top of those use cases. Of course, there are limits to that kind of non-structured approach and discussions like these are signals that we may be starting to reach them. :)

As @v1v has alluded to, there are some existing solutions which we've rolled out which require that JUnit output be produced. He's already mentioned the flaky test analyzer and based on reading the comments above, it sounds as if that's not of particularly high utility to this team (which is fine, of course). 

He's also mentioned more forward-looking efforts, like pipeline observability, and as mentioned, in its present form also makes use of JUnit output. There are some rather interesting proposals being kicked around in that vein for future enhancements, such as the ability to have the CI make determinations about which specific commit may have introduced a defect.

Another consideration, also previously alluded to by @v1v is that we're constantly trying to balance two competing interests. Of course we want teams to have a workflow that's maximally productive for themselves and their contributors but we also hear from folks who feel quite strongly that they want to see consistency in the contribution experience between projects in Observability. So, we need to strike a balance between consistency and flexibility.

A final consideration is that there has been a lot of talk, especially recently, about quality metrics for the Observability solution from end-to-end. Some standardization in the test result output paves that road more easily than having to account for different formats, etc. 

All of this, of course, is a bit of a long-winded way of saying that the question about contracts is a good question without a great answer. (Yet!) IMHO, it's not realistic nor just to expect people to suddenly adhere to a contract that they weren't aware of. We've been fortunate up to this point because it's just been happenstance that we've dealt with JUnit everywhere.  We'd like to continue with this practice if we can and it sounds from reading this issue as if there's still a path to do that here, which is being referred to as "option 3". 

> As a data point, the main reasons I appreciate the GH Actions we use on this repo for testing:

I'm extremely sympathetic to this point, TBH. We've been applying a lot of pressure in the needed places recently to try to make progress in terms of lowering the provisioning time for a worker instance. I would like to see us get to a point where the Jenkins infrastructure can be equally performant and get you test results just as fast, if not faster. There's a fair amount of momentum to try to get use there and testing to find the right approach is ongoing. IMHO, the current delay in worker provisioning is untenable for a number of use cases, such as those that you've highlighted.

> Put another way -- what can we do to avoid similiar breaking changes that don't show up on anyone's radar for four months? ;)

I'd be lying if I said I had a perfect answer for you here. This has really highlighted for me our need to be a bit more prescriptive in terms of how we define the boundary between teams when it comes to the CI. I'll commit to working more on some guidelines that we can present to teams but of course we'll need some time to fully flesh those out and it would be premature to try to just to toss out a few in the interest of trying to resolve this specific issue. We'll commit to trying to figure this out, though, and would welcome feedback on drafts once we put something together.
