### ISSUE TITLE
Total memory is incorrect for K8S Pod with resource limit

### ISSUE THREAD

**Issue by kurigashvili-godaddy** [elastic/apm-agent-nodejs#2490]
**Describe the bug**

If a K8S pod has [resource limit applied](https://www.densify.com/kubernetes-tools/kubernetes-resource-limits), the system.memory.total reported as total memory on the node where the pod is running instead of total memory available for pod.
https://github.com/elastic/apm-agent-nodejs/blob/b1a4dcd1e3cd7ac497f85f534aaedcab334e5c5f/lib/metrics/platforms/generic/index.js#L15

It makes this metric kind of useless when using K8S pods with resource limits.

**To Reproduce**

Spin kubernetes pod with resource limit for memory. Run `os.totalmem()` in node repl, the total memory would be total memory for node and not for a pod.

**Expected behavior**

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 12.22.1
- APM Server version: 7.15.2
- Agent version: 3.20.0

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by astorm** [comment]
Thanks for reporting @kurigashvili-godaddy.  

We've got a few clarifying questions.

1. Do you know what container system you're using with K8s? (Docker, containerd, LXS, etc.)

2. Is the issue here that you believe `system.memory.total` should report the value that's limited by your K8s configuration, or is the issue here that the K8 limits simply aren't available for monitoring at all and you'd like to see those in addition to `system.memory.total`

3. Is there a "Node.js available value" you think is better used here, or is this a case of wanting to see information about the configuration of the current pod when you're running in a K8s environment?

If you could could answer as many of these as possible it would help move this issue along and come up with the right solution.

**Comment by kurigashvili-godaddy** [comment]
@astorm 
1. containerd
2 and 3 - I am not sure what is the best way to handle.

Our use case: send an alert if a container approaches 80% of its available memory.
Currently we cannot do it using data from apm.
For example: node has 4GB but container is limited to 1GB. If container uses 900 MB of memory, we see on the APM dashboard 900MB out of 4GB.

We are currently using Metricbeat and it solves the issue for us.

kubernetes.container.memory.usage.limit.pct
kubernetes.container.memory.limit.bytes
kubernetes.container.memory.available.bytes

https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-kubernetes.html
