### ISSUE TITLE
elastic apm node with @angular-devkit/build-angular:browser builder

### ISSUE THREAD

**Issue by khaledtahaQ** [elastic/apm-agent-nodejs#3357]
i'm trying to add elastic node apm and I'm getting this error at build time 

./node_modules/elastic-apm-node/lib/config.js:20:14-43 - Error: Module not found: Error: Can't resolve '../package' in '/node_modules/elastic-apm-node/lib'

does anyone have an idea how to fix this?

**Comment by david-luna** [comment]
Hi @khaledtahaQ 

AFAIK `@angular-devkit/build-angular` is a set of builders & tools for Angular apps which run in the browser and not in a node environment.

Could you explain a bit more what's your use case?

**Comment by khaledtahaQ** [comment]
hi @david-luna  
im using node express server to run angular app , and I want to add elastic-apm-node to it ,but I get  this error 
`./node_modules/elastic-apm-node/lib/config.js:20:14-43 - Error: Module not found: Error: Can't resolve '../package' in '/node_modules/elastic-apm-node/lib' `at build time

**Comment by khaledtahaQ** [comment]
im using `nguniversal/builders`

**Comment by david-luna** [comment]
I was able to reproduce in a new app with angular universal. See  the repo
https://github.com/david-luna/elastic-nodejs-agent-angular-universal

Not only the node agent but other dependencies are affected.
```
Build at: 2023-05-17T13:57:22.845Z - Hash: 6465d6ca8b6dfa95 - Time: 1363ms
✔ Server application bundle generation complete.

./node_modules/elastic-apm-node/lib/agent.js:255:12-55 - Warning: Critical dependency: the request of a dependency is an expression

./node_modules/elastic-apm-node/lib/config.js:840:13-30 - Warning: Critical dependency: the request of a dependency is an expression

./node_modules/elastic-apm-node/lib/instrumentation/azure-functions.js:301:11-43 - Warning: Module not found: Error: Can't resolve '@azure/functions-core' in '/Users/david/Documents/repos/dl/elastic-nodejs-agent-angular-universal/node_modules/elastic-apm-node/lib/instrumentation'

./node_modules/elastic-apm-node/lib/instrumentation/index.js:253:16-30 - Warning: Critical dependency: the request of a dependency is an expression

./node_modules/fast-json-stringify/index.js:14:11-33 - Warning: Module not found: Error: Can't resolve 'long' in '/Users/david/Documents/repos/dl/elastic-nodejs-agent-angular-universal/node_modules/fast-json-stringify'

./node_modules/pino/lib/tools.js:170:26-62 - Warning: Module not found: Error: Can't resolve 'pino-pretty' in '/Users/david/Documents/repos/dl/elastic-nodejs-agent-angular-universal/node_modules/pino/lib'



./node_modules/elastic-apm-node/lib/agent.js:42:14-43 - Error: Module not found: Error: Can't resolve '../package' in '/Users/david/Documents/repos/dl/elastic-nodejs-agent-angular-universal/node_modules/elastic-apm-node/lib'

./node_modules/elastic-apm-node/lib/config.js:15:14-43 - Error: Module not found: Error: Can't resolve '../package' in '/Users/david/Documents/repos/dl/elastic-nodejs-agent-angular-universal/node_modules/elastic-apm-node/lib'
```

This is because because on how Webpack treats the requires. There is an explanation in the [docs](https://www.elastic.co/guide/en/apm/agent/nodejs/current/starting-the-agent.html#start-webpack)

Angular CLI builders have their own internal Webpack config and it's not trivial to change it. Luckily `angular.json` provides a set of properties to change a bit these configs. This [commit](https://github.com/david-luna/elastic-nodejs-agent-angular-universal/commit/f64768c70699bee667767ddeb966dee2e16f3228) add the instrumentation in the server using import and tweaks `angular.json` to treat the agent as external.
