### ISSUE TITLE
Dynamic serviceName or split APM instance?

### ISSUE THREAD

**Issue by intech** [elastic/apm-agent-nodejs#376]
On the microservice architecture, I would like to single out the Gateway API from the internal calls of the framework to the microservices using the transport protocol.
It is necessary for the error transaction groups to be separated.

I see 2 solutions to the problem:
Add the setServiceName () function to dynamically change as with transactions. Looked at request.js and make a conclusion that this is not an easy task, you need to allocate it to the transaction level. Or I misuse the tool.

The second solution is to initialize several instances within the same application. But you need a tool to manage these instances, the general queue for sending logs and support for common settings.

**Comment by watson** [comment]
It sounds like your root issue is that you want better control over the error grouping correct? You don't necessarily want the errors to be grouped under different services, just as long as they are not grouped together right?

**Comment by intech** [comment]
The first problem in combining the http error from the Transport Error Gateway API is between the micro services.

The second problem is related to the common list of all calls and gluing them in the transaction. I want to divide them into different layers of the application:
gateway, internal transport, services

**Comment by watson** [comment]
Ah I think maybe I understand now: You have a Node.js process that accepts requests via an HTTP API. It then routes the request through some internal logic, and finally forwards the request to another service/process. And today each request to the API is captured as a single big transaction in Elastic APM covering the entire journey, but instead you want 3 separate transactions, for for each part of the journey - both so that errors occurring in each individual part are kept separate, but also so you can view the transaction for each part separately. Is that correctly understood?

**Comment by intech** [comment]
Yes, right!

**Comment by watson** [comment]
It's currently not possible to stop the agent from creating a new transaction automatically when it detects an incoming HTTP request. It will also expect to be able to end it once the HTTP request finishes. That would be required if you wished to create other smaller transactions instead of the default single transactions. But I currently don't think it would be right thing to do anyway.

In general, the error grouping that occurs in the APM UI does not take into account the name of the corresponding transaction (if you're interested you can see the algorithm [here](https://github.com/elastic/apm-server/blob/a1e7afa201d41a771508467058c5e81b43ab7712/processor/error/event.go#L236-L269)). So the splitting of transactions will not help you in grouping your errors in the UI.

If you wish to see how long the 3 different parts of your code base each take, I instead recommend starting a [custom span](https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-spans.html) when an HTTP request is first received and ending it when it reaches your inner logic. From there you start a new span and end that just before sending it off to your other services and so forth. This way you will see a span waterfall representing your 3 different logical parts.

Would this solve your issues?

**Comment by intech** [comment]
I'll try to follow your advice, thank you.
As a result, will I receive a duplication span in different transactions?

**Comment by intech** [comment]
I mean automatic transactions intercepted by http/https by the agent itself.
I still use the custom span, but I need to examine the portion of the code that you provided with the grouping in order to disentangle itself more in your problem.
I will write later about the results if you do not close the problem.

**Comment by watson** [comment]
Ah, got it. Yeah, we differentiate between transactions and spans. In many ways they are very similar. Both have a name, type, a start time and a duration. You could actually think of a transaction as just the root span in a given service, under which zero or more spans can be associated. So you can only have one active transaction in the current program context at a time. So if you where to create a new transaction manually during an HTTP request, it would essentially "overwrite" the one created by the agent and that would have unintended side effects - so it's not recommended.

**Comment by watson** [comment]
@intech Did you find a good solution to your problem? I was wondering if I could close this issue. If you still have questions or think something in Elastic APM could be improved to better support your use-case, let me know 😃

**Comment by intech** [comment]
@watson all ok, can close
