### ISSUE TITLE
[APM-CI][Node.js] Smarter TAV tests

### ISSUE THREAD

**Issue by Qard** [elastic/apm-agent-nodejs#378]
Currently the entire TAV test suite runs on every PR, which often isn't necessary. I'm thinking it would be a good idea to write a script to detect which modules changed, if any, and run only those parts of the TAV test suite on PRs. We'd then leave running the full suite up to a regular cron job. This should help to significantly cut down CI feedback time on PRs.

**Comment by alvarolobato** [comment]
This will be improved with the new build system we are working on.

**Comment by kuisathaverat** [comment]
duplicated https://github.com/elastic/apm-agent-nodejs/issues/1152

**Comment by watson** [comment]
These are two different issues. We already have the feature described in #1152 running on Travis, just not on Jenkins. This issue is for making that feature even smarter.

**Comment by kuisathaverat** [comment]
for us, it is mostly the same, the trigger for the test stage is a path match in the changes, for example, if you have changes on the path /module/my_module it will trigger the TAV test for that module.

**Comment by watson** [comment]
The other issue is of higher importance and also covers what happens when you merge into master and how scheduled builds behave. This issue is only about PR builds. But if you want to cover both issues in a single fix and it doesn't take much longer to do, that would be awesome 😃 In that case, there are a few things we need for it in order to work with our workflow (these all concern them selfs with PR builds - scheduled builds and branch builds are not covered by this issue):

- We need the TAV tests for a given module to run automatically only if the corresponding module file has been updated in `lib/instrumentation/modules/*` or in `test/instrumentation/modules/*`.
- Even if no changes have been made to a given module file or module test file(s), we need to be able to manually trigger running its TAV tests.
- We also need a way to manually trigger running _all_ TAV tests.

**Comment by v1v** [comment]
> - We need the TAV tests for a given module to run automatically only if the corresponding module file has been updated in lib/instrumentation/modules/* or in test/instrumentation/modules/*.

This is something feasible.

> - Even if no changes have been made to a given module file or module test file(s), we need to be able to manually trigger running its TAV tests.

That's not really easy to solve though. I'd rather say let's keep this particular requirement outside of this scope for now.

> - We also need a way to manually trigger running all TAV tests.

This is something doable. 

I'll start working on this particular issue now.

**Comment by kuisathaverat** [comment]
>We also need a way to manually trigger running all TAV tests.

It could be a job that you can trigger manually or with a comment from GitHub, basically a pipeline with the comment trigger.

**Comment by v1v** [comment]
Since the current trigger by comment is based on the regex `(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*`:
- https://github.com/elastic/apm-agent-nodejs/blob/master/Jenkinsfile#L27

I'd suggest using the comment `jenkins run the tests for the tav _module_` for instance:
- `jenkins run the tests for the tav mysql`
- `jenkins run the tests for the tav finalhandler`

Even we could potentially extend to run a list of modules as long as they are split in `,`:
- `jenkins run the tests for the tav finalhandler,mysql,redis`

From the implementation point of view, we are working on exposing those github comments with the env variable `GITHUB_COMMENT`

_NOTE_: if we agree about this, a few questions:
- Do we want to keep the GitHub check called `TAV Test` as executed even though it did run a subset of tests? Or do we want to skip the GitHub check as long as it's triggered with a comment? Or create a new GitHub check called something like `TAV Test Subset`?

**Comment by Qard** [comment]
Maybe change the name to indicate it was comment-triggered?

Also, it might be good to do something like "jenkins run the _module_ tests" to differentiate between the test suite modes. 🤔

**Comment by v1v** [comment]
> Maybe change the name to indicate it was comment-triggered?

What do you think the below one when running the TAVs for the comment triggered?

![image](https://user-images.githubusercontent.com/2871786/61624193-0b745a00-ac70-11e9-9088-80e031f801ec.png)

> Also, it might be good to do something like "jenkins run the module tests" to differentiate between the test suite modes. 

I don't understand, this proposal was about adding a comment to run specific TAV modules, if required we can potentially add more use cases in the future by creating some issues. What do you mean with this?

**Comment by Qard** [comment]
I was just referring just to the grammar of `jenkins run the tests for the module ...` versus `jenkins run the module tests for ...`.
