### ISSUE TITLE
Support for multiple APM servers in serverUrl config

### ISSUE THREAD

**Issue by JherezTaylor** [elastic/apm-agent-nodejs#447]
As titled, the other Elasticstack products typically accept the URL parameter as a concated IP:port string. It would be useful if the APM agent can operate in the same manner and round robin between the supplied servers.

**Comment by watson** [comment]
Hi @JherezTaylor 👋  Good idea. I'll add it to our todo list 😅

**Comment by watson** [comment]
Btw, for now we recommend that you deploy a load balancer in front of your APM Servers and handle it that way. But I agree your approach would be easier.

**Comment by watson** [comment]
I'm not sure if this is relevant for your setup, but it's also possible to install the APM Server on the same machine as where app with the agent is running. So each machine have its own agent that all send data to the same Elasticsearch cluster. If you go down that road, it's even possible to connect to the APM Server using Unix Domain Sockets instead of TCP. So there's no need for routing or opening up any ports at all.

**Comment by AlexanderWert** [comment]
Closed as decided in https://github.com/elastic/apm/issues/359
