### ISSUE TITLE
Limit the length for non-keyword fields

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-nodejs#630]
Currently only the keyword fields are limited at 1024 characters, we need to also apply this limit to non keyword fields. There will also be extended fields ie. SQL that can go up to 10000 characters to non-keyword fields.

**Comment by watson** [comment]
For reference: The Node.js agent already truncates a few other fields:

- The config option [`errorMessageMaxLength`](https://www.elastic.co/guide/en/apm/agent/nodejs/master/agent-api.html#error-message-max-length) can be used to truncate the error message. It defaults to 2048 bytes (not chars)

- We also truncate the HTTP body (in case the agent is configured to capture it using [`captureBody`](https://www.elastic.co/guide/en/apm/agent/nodejs/master/agent-api.html#capture-body)) to 2048 bytes (not chars)

We need to decide if we should keep these lower limits as well as also adding a general upper limit of 10.000 characters, and if we should switch these limits to be characters instead of bytes.
