### ISSUE TITLE
Use const, let etc in all documentation

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#640]
We still use `var` in quite a few places in the source code for historical reasons, and that's ok. But it would be nicer if we updated our documentation to show more modern code examples.

**Comment by FowiFlowi** [comment]
What about to replace it not only in docs? I have already done it btw

**Comment by bmorelli25** [comment]
Another issue that relates to this one is using callouts instead of comments in the code samples. Here's what I'm referring to. I'm curious as to if you have preferences one way or the other? @Qard @watson :

**Current code snippets use comments:**
<img width="765" alt="screen shot 2018-12-04 at 1 30 57 pm" src="https://user-images.githubusercontent.com/5618806/49474456-93811e80-f7c9-11e8-8c6c-a7b3d1048bc4.png">

**The same code using callouts instead:**
<img width="767" alt="screen shot 2018-12-04 at 1 34 19 pm" src="https://user-images.githubusercontent.com/5618806/49474457-95e37880-f7c9-11e8-8e2d-1220c40dc1db.png">

**Comment by watson** [comment]
Hmm... I agree it does looks cleaner, but I kind of like that when you copy and paste the other example, you get the comments with you to your source code. For that reason I would actually personally prefer the inline comments. But I'd be interested to hear what @Qard thinks.

**Comment by Qard** [comment]
Code comments feel more natural to me. The callouts thing seems like it'd be somewhat unfamiliar/confusing to anyone that hasn't seen that aspect of the UI before. 🤔

**Comment by bmorelli25** [comment]
Thanks for the feedback guys. Your concerns make sense, and I'm good with leaving as-is.

**Comment by watson** [comment]
@FowiFlowi I think it's best to just focus on documentation in this issue. The benefit of updating all the code to use const/let doesn't outweigh the risk, so for now I'd like to only update it incrementally when we refactor different parts of the system anyway 😃 

Btw, until recently, using const/let would actually make your code slower as v8 wasn't optimized for that use-case. In more recent versions of Node.js this speed difference is negligible though.
