### ISSUE TITLE
Framework name and version not always correctly detected

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#688]
For details see elastic/apm-integration-testing#241

**Comment by Qard** [comment]
The problem is that the `framework*` properties are given to the http client when `start(...)` is called while the framework properties are not _updated_ until a framework module is loaded. We'll have to either change the http client to allow setting the framework properties later and resending the metadata event, or figuring out the framework somehow during the `start(...)` call--reading the `package.json` maybe?

**Comment by watson** [comment]
Interesting. At what point will a request be made to the APM Server _before_ the framework have been required?! Maybe if a bug happens after `start` have been called but before the framework have been required. This seems like an extreme edge case though. What do you think?

**Comment by Qard** [comment]
It's not that the metadata event is sent before the framework is required, it's that the field is given to the http client before the framework is required. There's no way to update the settings after the http client is constructed in the agent start method.

**Comment by watson** [comment]
Ah, I see. We also talked about this in regards to instrumenting Kibana, where the serverUrl isn't known before a while after initiating the transport. It would probably make sense to fix both of these issues in the same way.
