### ISSUE TITLE
instrument: false should disable automatic instrumentation

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#858]
Today setting `instrument: false` will disable both automatic and manual instrumentation. This doesn't really make any sense. Instead I think this option should only disable automatic instrumentation.

This should probably be coordinated with the other agents. Today we seem to all have implemented `instrument` a little bit differently. E.g. in Python setting it to `false`, will only disable automatic creation of spans, in Java it will allow manual instrumentation, in Ruby and Node.js it will not etc.

**Comment by watson** [comment]
The sematics of how this should work have now been ironed out: https://github.com/elastic/apm/issues/49

**Comment by blakeembrey** [comment]
@watson Can we change this at all? The automatic instrumentation isn't usable in AWS lambda when using Webpack since it'll never read any of the files, which overall just adds to payload size/latency of the deployed file. I'd even love if it were disabled by default and you could instantiate it later, e.g. https://github.com/RisingStack/opentracing-auto.

**Comment by watson** [comment]
@blakeembrey I'm not sure what you mean?

**Comment by blakeembrey** [comment]
@watson Sorry, I'm agreeing with the original post you made with anecdotal evidence to reinforce the reason disabling automatic tracing would be useful (e.g. perf overhead in Webpack where the tracing hook doesn't work anyway).
