### ISSUE TITLE
Consider using const and let

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#99]
Since we recently dropped support for versions of Node.js older than v4, I've been wondering if there would be a benefit to switching to use `const` and `let` internally instead of `var`.

I personally don't mind using `var`, and as far as I know up until recently V8 would actually not perform as good with `const` as it would with `var`. But I expect this have since been improved upon, so it might be worth looking into.

There's of course also the option of just starting to use `const` and `let` in new code, but not going back and refactoring the old code. It would be kind of an eyesore though, so I hope it's easy to switch everything in one big monster commit.

If we decide to switch to using `const` and `let` we should also make sure to update our documentation code examples to use `const` and `let`.

Please comment with pro's and con's below - and please stay civil 😅

**Comment by watson** [comment]
cc @Qard

**Comment by Qard** [comment]
I've been using const/let in all my personal code for quite awhile now.

The nice thing about const/let is that you can't rebind them in keyword form, so you don't get confusing errors when you do something like this:

```js
var thing = 1
if (condition) {
  var thing = 2
  useInternalThing(thing)
}
useExternalThing(thing)
```

If the `var` was `let` or `const`, it'd throw an error complaining about rebinding. With `var` it'll just happily replace the existing reference.

My personal style is to make everything `const` until proven it needs to be mutable. Linters are generally pretty good about detecting that and complaining when your code tries to mutate a `const`.

The performance issues are largely conditional, the main one being that reassigning a `let` in a loop body used to deopt. (NOTE: loop body, not loop condition statements, so that does *not* include the incrementer component.)

FYI: A simple search and replace wouldn't work as I know there are at least a few cases like `if (condition) { var foo = 'bar' }` that would no longer get hoisted out of the block.

**Comment by watson** [comment]
@Qard thanks :) Out of curiosity, do you remember when the `let` loop body reassignment issue was fixed? Is that still the case in Node 6 for instance?

I've also started using `const` and `let` now in my personal code... it took me quite a while 😅

**Comment by Qard** [comment]
If I recall correctly, it was fixed in early 6.x releases. I don't remember the exact version, but not 6.0.0.

**Comment by watson** [comment]
We should probably wait with this until we drop support for 4.x.

Would be interesting to get some numbers on this as well: https://twitter.com/stephenbelanger/status/952988762421706753

**Comment by watson** [comment]
Note to self: If we make a PR with these changes, we should benchmark it against master to see if there's any performance gains or degradations

**Comment by alvarolobato** [comment]
We agreed to start using `let` and `const` on new code and refactors. We won't do a major refactor of all the code.
